// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: risk/v1/risk.proto

package riskv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RiskService_CheckOrder_FullMethodName               = "/eidos.risk.v1.RiskService/CheckOrder"
	RiskService_CheckWithdrawal_FullMethodName          = "/eidos.risk.v1.RiskService/CheckWithdrawal"
	RiskService_CheckTransaction_FullMethodName         = "/eidos.risk.v1.RiskService/CheckTransaction"
	RiskService_AddToBlacklist_FullMethodName           = "/eidos.risk.v1.RiskService/AddToBlacklist"
	RiskService_RemoveFromBlacklist_FullMethodName      = "/eidos.risk.v1.RiskService/RemoveFromBlacklist"
	RiskService_CheckBlacklist_FullMethodName           = "/eidos.risk.v1.RiskService/CheckBlacklist"
	RiskService_ListBlacklist_FullMethodName            = "/eidos.risk.v1.RiskService/ListBlacklist"
	RiskService_ListRiskRules_FullMethodName            = "/eidos.risk.v1.RiskService/ListRiskRules"
	RiskService_GetRiskRule_FullMethodName              = "/eidos.risk.v1.RiskService/GetRiskRule"
	RiskService_UpdateRiskRule_FullMethodName           = "/eidos.risk.v1.RiskService/UpdateRiskRule"
	RiskService_GetRateLimitStatus_FullMethodName       = "/eidos.risk.v1.RiskService/GetRateLimitStatus"
	RiskService_ResetRateLimit_FullMethodName           = "/eidos.risk.v1.RiskService/ResetRateLimit"
	RiskService_ListRiskEvents_FullMethodName           = "/eidos.risk.v1.RiskService/ListRiskEvents"
	RiskService_GetRiskEvent_FullMethodName             = "/eidos.risk.v1.RiskService/GetRiskEvent"
	RiskService_AcknowledgeRiskEvent_FullMethodName     = "/eidos.risk.v1.RiskService/AcknowledgeRiskEvent"
	RiskService_GetUserLimits_FullMethodName            = "/eidos.risk.v1.RiskService/GetUserLimits"
	RiskService_SetUserLimits_FullMethodName            = "/eidos.risk.v1.RiskService/SetUserLimits"
	RiskService_FreezeAccount_FullMethodName            = "/eidos.risk.v1.RiskService/FreezeAccount"
	RiskService_UnfreezeAccount_FullMethodName          = "/eidos.risk.v1.RiskService/UnfreezeAccount"
	RiskService_GetAccountStatus_FullMethodName         = "/eidos.risk.v1.RiskService/GetAccountStatus"
	RiskService_GetRiskStats_FullMethodName             = "/eidos.risk.v1.RiskService/GetRiskStats"
	RiskService_ListWithdrawalReviews_FullMethodName    = "/eidos.risk.v1.RiskService/ListWithdrawalReviews"
	RiskService_GetWithdrawalReview_FullMethodName      = "/eidos.risk.v1.RiskService/GetWithdrawalReview"
	RiskService_ApproveWithdrawalReview_FullMethodName  = "/eidos.risk.v1.RiskService/ApproveWithdrawalReview"
	RiskService_RejectWithdrawalReview_FullMethodName   = "/eidos.risk.v1.RiskService/RejectWithdrawalReview"
	RiskService_GetWithdrawalReviewStats_FullMethodName = "/eidos.risk.v1.RiskService/GetWithdrawalReviewStats"
)

// RiskServiceClient is the client API for RiskService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// RiskService provides risk management functionality including:
// - Pre-trade risk checks (order, withdrawal)
// - Blacklist management
// - Risk rule configuration
// - Rate limiting
// - Risk event monitoring
type RiskServiceClient interface {
	// CheckOrder validates an order against risk rules
	// Called before order is sent to matching engine
	CheckOrder(ctx context.Context, in *CheckOrderRequest, opts ...grpc.CallOption) (*CheckOrderResponse, error)
	// CheckWithdrawal validates a withdrawal against risk rules
	// Called before withdrawal is processed
	CheckWithdrawal(ctx context.Context, in *CheckWithdrawalRequest, opts ...grpc.CallOption) (*CheckWithdrawalResponse, error)
	// CheckTransaction validates a generic transaction
	CheckTransaction(ctx context.Context, in *CheckTransactionRequest, opts ...grpc.CallOption) (*CheckTransactionResponse, error)
	// AddToBlacklist adds a wallet to the blacklist
	AddToBlacklist(ctx context.Context, in *AddToBlacklistRequest, opts ...grpc.CallOption) (*AddToBlacklistResponse, error)
	// RemoveFromBlacklist removes a wallet from the blacklist
	RemoveFromBlacklist(ctx context.Context, in *RemoveFromBlacklistRequest, opts ...grpc.CallOption) (*RemoveFromBlacklistResponse, error)
	// CheckBlacklist checks if a wallet is blacklisted
	CheckBlacklist(ctx context.Context, in *CheckBlacklistRequest, opts ...grpc.CallOption) (*CheckBlacklistResponse, error)
	// ListBlacklist retrieves the blacklist with filters
	ListBlacklist(ctx context.Context, in *ListBlacklistRequest, opts ...grpc.CallOption) (*ListBlacklistResponse, error)
	// ListRiskRules retrieves all risk rules
	ListRiskRules(ctx context.Context, in *ListRiskRulesRequest, opts ...grpc.CallOption) (*ListRiskRulesResponse, error)
	// GetRiskRule retrieves a specific risk rule
	GetRiskRule(ctx context.Context, in *GetRiskRuleRequest, opts ...grpc.CallOption) (*GetRiskRuleResponse, error)
	// UpdateRiskRule updates a risk rule
	UpdateRiskRule(ctx context.Context, in *UpdateRiskRuleRequest, opts ...grpc.CallOption) (*UpdateRiskRuleResponse, error)
	// GetRateLimitStatus retrieves rate limit status for a wallet
	GetRateLimitStatus(ctx context.Context, in *GetRateLimitStatusRequest, opts ...grpc.CallOption) (*GetRateLimitStatusResponse, error)
	// ResetRateLimit resets rate limit counters for a wallet
	ResetRateLimit(ctx context.Context, in *ResetRateLimitRequest, opts ...grpc.CallOption) (*ResetRateLimitResponse, error)
	// ListRiskEvents retrieves risk events with filters
	ListRiskEvents(ctx context.Context, in *ListRiskEventsRequest, opts ...grpc.CallOption) (*ListRiskEventsResponse, error)
	// GetRiskEvent retrieves a specific risk event
	GetRiskEvent(ctx context.Context, in *GetRiskEventRequest, opts ...grpc.CallOption) (*GetRiskEventResponse, error)
	// AcknowledgeRiskEvent acknowledges a risk event
	AcknowledgeRiskEvent(ctx context.Context, in *AcknowledgeRiskEventRequest, opts ...grpc.CallOption) (*AcknowledgeRiskEventResponse, error)
	// GetUserLimits retrieves limits for a user
	GetUserLimits(ctx context.Context, in *GetUserLimitsRequest, opts ...grpc.CallOption) (*GetUserLimitsResponse, error)
	// SetUserLimits sets custom limits for a user
	SetUserLimits(ctx context.Context, in *SetUserLimitsRequest, opts ...grpc.CallOption) (*SetUserLimitsResponse, error)
	// FreezeAccount freezes a user account
	FreezeAccount(ctx context.Context, in *FreezeAccountRequest, opts ...grpc.CallOption) (*FreezeAccountResponse, error)
	// UnfreezeAccount unfreezes a user account
	UnfreezeAccount(ctx context.Context, in *UnfreezeAccountRequest, opts ...grpc.CallOption) (*UnfreezeAccountResponse, error)
	// GetAccountStatus retrieves account risk status
	GetAccountStatus(ctx context.Context, in *GetAccountStatusRequest, opts ...grpc.CallOption) (*GetAccountStatusResponse, error)
	// GetRiskStats retrieves risk statistics
	GetRiskStats(ctx context.Context, in *GetRiskStatsRequest, opts ...grpc.CallOption) (*GetRiskStatsResponse, error)
	// ListWithdrawalReviews retrieves pending withdrawal reviews
	ListWithdrawalReviews(ctx context.Context, in *ListWithdrawalReviewsRequest, opts ...grpc.CallOption) (*ListWithdrawalReviewsResponse, error)
	// GetWithdrawalReview retrieves a specific withdrawal review
	GetWithdrawalReview(ctx context.Context, in *GetWithdrawalReviewRequest, opts ...grpc.CallOption) (*GetWithdrawalReviewResponse, error)
	// ApproveWithdrawalReview approves a withdrawal review
	ApproveWithdrawalReview(ctx context.Context, in *ApproveWithdrawalReviewRequest, opts ...grpc.CallOption) (*ApproveWithdrawalReviewResponse, error)
	// RejectWithdrawalReview rejects a withdrawal review
	RejectWithdrawalReview(ctx context.Context, in *RejectWithdrawalReviewRequest, opts ...grpc.CallOption) (*RejectWithdrawalReviewResponse, error)
	// GetWithdrawalReviewStats retrieves withdrawal review statistics
	GetWithdrawalReviewStats(ctx context.Context, in *GetWithdrawalReviewStatsRequest, opts ...grpc.CallOption) (*GetWithdrawalReviewStatsResponse, error)
}

type riskServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRiskServiceClient(cc grpc.ClientConnInterface) RiskServiceClient {
	return &riskServiceClient{cc}
}

func (c *riskServiceClient) CheckOrder(ctx context.Context, in *CheckOrderRequest, opts ...grpc.CallOption) (*CheckOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckOrderResponse)
	err := c.cc.Invoke(ctx, RiskService_CheckOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *riskServiceClient) CheckWithdrawal(ctx context.Context, in *CheckWithdrawalRequest, opts ...grpc.CallOption) (*CheckWithdrawalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckWithdrawalResponse)
	err := c.cc.Invoke(ctx, RiskService_CheckWithdrawal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *riskServiceClient) CheckTransaction(ctx context.Context, in *CheckTransactionRequest, opts ...grpc.CallOption) (*CheckTransactionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckTransactionResponse)
	err := c.cc.Invoke(ctx, RiskService_CheckTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *riskServiceClient) AddToBlacklist(ctx context.Context, in *AddToBlacklistRequest, opts ...grpc.CallOption) (*AddToBlacklistResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddToBlacklistResponse)
	err := c.cc.Invoke(ctx, RiskService_AddToBlacklist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *riskServiceClient) RemoveFromBlacklist(ctx context.Context, in *RemoveFromBlacklistRequest, opts ...grpc.CallOption) (*RemoveFromBlacklistResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveFromBlacklistResponse)
	err := c.cc.Invoke(ctx, RiskService_RemoveFromBlacklist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *riskServiceClient) CheckBlacklist(ctx context.Context, in *CheckBlacklistRequest, opts ...grpc.CallOption) (*CheckBlacklistResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckBlacklistResponse)
	err := c.cc.Invoke(ctx, RiskService_CheckBlacklist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *riskServiceClient) ListBlacklist(ctx context.Context, in *ListBlacklistRequest, opts ...grpc.CallOption) (*ListBlacklistResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBlacklistResponse)
	err := c.cc.Invoke(ctx, RiskService_ListBlacklist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *riskServiceClient) ListRiskRules(ctx context.Context, in *ListRiskRulesRequest, opts ...grpc.CallOption) (*ListRiskRulesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRiskRulesResponse)
	err := c.cc.Invoke(ctx, RiskService_ListRiskRules_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *riskServiceClient) GetRiskRule(ctx context.Context, in *GetRiskRuleRequest, opts ...grpc.CallOption) (*GetRiskRuleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRiskRuleResponse)
	err := c.cc.Invoke(ctx, RiskService_GetRiskRule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *riskServiceClient) UpdateRiskRule(ctx context.Context, in *UpdateRiskRuleRequest, opts ...grpc.CallOption) (*UpdateRiskRuleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateRiskRuleResponse)
	err := c.cc.Invoke(ctx, RiskService_UpdateRiskRule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *riskServiceClient) GetRateLimitStatus(ctx context.Context, in *GetRateLimitStatusRequest, opts ...grpc.CallOption) (*GetRateLimitStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRateLimitStatusResponse)
	err := c.cc.Invoke(ctx, RiskService_GetRateLimitStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *riskServiceClient) ResetRateLimit(ctx context.Context, in *ResetRateLimitRequest, opts ...grpc.CallOption) (*ResetRateLimitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResetRateLimitResponse)
	err := c.cc.Invoke(ctx, RiskService_ResetRateLimit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *riskServiceClient) ListRiskEvents(ctx context.Context, in *ListRiskEventsRequest, opts ...grpc.CallOption) (*ListRiskEventsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRiskEventsResponse)
	err := c.cc.Invoke(ctx, RiskService_ListRiskEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *riskServiceClient) GetRiskEvent(ctx context.Context, in *GetRiskEventRequest, opts ...grpc.CallOption) (*GetRiskEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRiskEventResponse)
	err := c.cc.Invoke(ctx, RiskService_GetRiskEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *riskServiceClient) AcknowledgeRiskEvent(ctx context.Context, in *AcknowledgeRiskEventRequest, opts ...grpc.CallOption) (*AcknowledgeRiskEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AcknowledgeRiskEventResponse)
	err := c.cc.Invoke(ctx, RiskService_AcknowledgeRiskEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *riskServiceClient) GetUserLimits(ctx context.Context, in *GetUserLimitsRequest, opts ...grpc.CallOption) (*GetUserLimitsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserLimitsResponse)
	err := c.cc.Invoke(ctx, RiskService_GetUserLimits_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *riskServiceClient) SetUserLimits(ctx context.Context, in *SetUserLimitsRequest, opts ...grpc.CallOption) (*SetUserLimitsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetUserLimitsResponse)
	err := c.cc.Invoke(ctx, RiskService_SetUserLimits_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *riskServiceClient) FreezeAccount(ctx context.Context, in *FreezeAccountRequest, opts ...grpc.CallOption) (*FreezeAccountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FreezeAccountResponse)
	err := c.cc.Invoke(ctx, RiskService_FreezeAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *riskServiceClient) UnfreezeAccount(ctx context.Context, in *UnfreezeAccountRequest, opts ...grpc.CallOption) (*UnfreezeAccountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnfreezeAccountResponse)
	err := c.cc.Invoke(ctx, RiskService_UnfreezeAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *riskServiceClient) GetAccountStatus(ctx context.Context, in *GetAccountStatusRequest, opts ...grpc.CallOption) (*GetAccountStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAccountStatusResponse)
	err := c.cc.Invoke(ctx, RiskService_GetAccountStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *riskServiceClient) GetRiskStats(ctx context.Context, in *GetRiskStatsRequest, opts ...grpc.CallOption) (*GetRiskStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRiskStatsResponse)
	err := c.cc.Invoke(ctx, RiskService_GetRiskStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *riskServiceClient) ListWithdrawalReviews(ctx context.Context, in *ListWithdrawalReviewsRequest, opts ...grpc.CallOption) (*ListWithdrawalReviewsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListWithdrawalReviewsResponse)
	err := c.cc.Invoke(ctx, RiskService_ListWithdrawalReviews_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *riskServiceClient) GetWithdrawalReview(ctx context.Context, in *GetWithdrawalReviewRequest, opts ...grpc.CallOption) (*GetWithdrawalReviewResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWithdrawalReviewResponse)
	err := c.cc.Invoke(ctx, RiskService_GetWithdrawalReview_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *riskServiceClient) ApproveWithdrawalReview(ctx context.Context, in *ApproveWithdrawalReviewRequest, opts ...grpc.CallOption) (*ApproveWithdrawalReviewResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApproveWithdrawalReviewResponse)
	err := c.cc.Invoke(ctx, RiskService_ApproveWithdrawalReview_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *riskServiceClient) RejectWithdrawalReview(ctx context.Context, in *RejectWithdrawalReviewRequest, opts ...grpc.CallOption) (*RejectWithdrawalReviewResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RejectWithdrawalReviewResponse)
	err := c.cc.Invoke(ctx, RiskService_RejectWithdrawalReview_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *riskServiceClient) GetWithdrawalReviewStats(ctx context.Context, in *GetWithdrawalReviewStatsRequest, opts ...grpc.CallOption) (*GetWithdrawalReviewStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWithdrawalReviewStatsResponse)
	err := c.cc.Invoke(ctx, RiskService_GetWithdrawalReviewStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RiskServiceServer is the server API for RiskService service.
// All implementations must embed UnimplementedRiskServiceServer
// for forward compatibility.
//
// RiskService provides risk management functionality including:
// - Pre-trade risk checks (order, withdrawal)
// - Blacklist management
// - Risk rule configuration
// - Rate limiting
// - Risk event monitoring
type RiskServiceServer interface {
	// CheckOrder validates an order against risk rules
	// Called before order is sent to matching engine
	CheckOrder(context.Context, *CheckOrderRequest) (*CheckOrderResponse, error)
	// CheckWithdrawal validates a withdrawal against risk rules
	// Called before withdrawal is processed
	CheckWithdrawal(context.Context, *CheckWithdrawalRequest) (*CheckWithdrawalResponse, error)
	// CheckTransaction validates a generic transaction
	CheckTransaction(context.Context, *CheckTransactionRequest) (*CheckTransactionResponse, error)
	// AddToBlacklist adds a wallet to the blacklist
	AddToBlacklist(context.Context, *AddToBlacklistRequest) (*AddToBlacklistResponse, error)
	// RemoveFromBlacklist removes a wallet from the blacklist
	RemoveFromBlacklist(context.Context, *RemoveFromBlacklistRequest) (*RemoveFromBlacklistResponse, error)
	// CheckBlacklist checks if a wallet is blacklisted
	CheckBlacklist(context.Context, *CheckBlacklistRequest) (*CheckBlacklistResponse, error)
	// ListBlacklist retrieves the blacklist with filters
	ListBlacklist(context.Context, *ListBlacklistRequest) (*ListBlacklistResponse, error)
	// ListRiskRules retrieves all risk rules
	ListRiskRules(context.Context, *ListRiskRulesRequest) (*ListRiskRulesResponse, error)
	// GetRiskRule retrieves a specific risk rule
	GetRiskRule(context.Context, *GetRiskRuleRequest) (*GetRiskRuleResponse, error)
	// UpdateRiskRule updates a risk rule
	UpdateRiskRule(context.Context, *UpdateRiskRuleRequest) (*UpdateRiskRuleResponse, error)
	// GetRateLimitStatus retrieves rate limit status for a wallet
	GetRateLimitStatus(context.Context, *GetRateLimitStatusRequest) (*GetRateLimitStatusResponse, error)
	// ResetRateLimit resets rate limit counters for a wallet
	ResetRateLimit(context.Context, *ResetRateLimitRequest) (*ResetRateLimitResponse, error)
	// ListRiskEvents retrieves risk events with filters
	ListRiskEvents(context.Context, *ListRiskEventsRequest) (*ListRiskEventsResponse, error)
	// GetRiskEvent retrieves a specific risk event
	GetRiskEvent(context.Context, *GetRiskEventRequest) (*GetRiskEventResponse, error)
	// AcknowledgeRiskEvent acknowledges a risk event
	AcknowledgeRiskEvent(context.Context, *AcknowledgeRiskEventRequest) (*AcknowledgeRiskEventResponse, error)
	// GetUserLimits retrieves limits for a user
	GetUserLimits(context.Context, *GetUserLimitsRequest) (*GetUserLimitsResponse, error)
	// SetUserLimits sets custom limits for a user
	SetUserLimits(context.Context, *SetUserLimitsRequest) (*SetUserLimitsResponse, error)
	// FreezeAccount freezes a user account
	FreezeAccount(context.Context, *FreezeAccountRequest) (*FreezeAccountResponse, error)
	// UnfreezeAccount unfreezes a user account
	UnfreezeAccount(context.Context, *UnfreezeAccountRequest) (*UnfreezeAccountResponse, error)
	// GetAccountStatus retrieves account risk status
	GetAccountStatus(context.Context, *GetAccountStatusRequest) (*GetAccountStatusResponse, error)
	// GetRiskStats retrieves risk statistics
	GetRiskStats(context.Context, *GetRiskStatsRequest) (*GetRiskStatsResponse, error)
	// ListWithdrawalReviews retrieves pending withdrawal reviews
	ListWithdrawalReviews(context.Context, *ListWithdrawalReviewsRequest) (*ListWithdrawalReviewsResponse, error)
	// GetWithdrawalReview retrieves a specific withdrawal review
	GetWithdrawalReview(context.Context, *GetWithdrawalReviewRequest) (*GetWithdrawalReviewResponse, error)
	// ApproveWithdrawalReview approves a withdrawal review
	ApproveWithdrawalReview(context.Context, *ApproveWithdrawalReviewRequest) (*ApproveWithdrawalReviewResponse, error)
	// RejectWithdrawalReview rejects a withdrawal review
	RejectWithdrawalReview(context.Context, *RejectWithdrawalReviewRequest) (*RejectWithdrawalReviewResponse, error)
	// GetWithdrawalReviewStats retrieves withdrawal review statistics
	GetWithdrawalReviewStats(context.Context, *GetWithdrawalReviewStatsRequest) (*GetWithdrawalReviewStatsResponse, error)
	mustEmbedUnimplementedRiskServiceServer()
}

// UnimplementedRiskServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRiskServiceServer struct{}

func (UnimplementedRiskServiceServer) CheckOrder(context.Context, *CheckOrderRequest) (*CheckOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckOrder not implemented")
}
func (UnimplementedRiskServiceServer) CheckWithdrawal(context.Context, *CheckWithdrawalRequest) (*CheckWithdrawalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckWithdrawal not implemented")
}
func (UnimplementedRiskServiceServer) CheckTransaction(context.Context, *CheckTransactionRequest) (*CheckTransactionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckTransaction not implemented")
}
func (UnimplementedRiskServiceServer) AddToBlacklist(context.Context, *AddToBlacklistRequest) (*AddToBlacklistResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddToBlacklist not implemented")
}
func (UnimplementedRiskServiceServer) RemoveFromBlacklist(context.Context, *RemoveFromBlacklistRequest) (*RemoveFromBlacklistResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveFromBlacklist not implemented")
}
func (UnimplementedRiskServiceServer) CheckBlacklist(context.Context, *CheckBlacklistRequest) (*CheckBlacklistResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckBlacklist not implemented")
}
func (UnimplementedRiskServiceServer) ListBlacklist(context.Context, *ListBlacklistRequest) (*ListBlacklistResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListBlacklist not implemented")
}
func (UnimplementedRiskServiceServer) ListRiskRules(context.Context, *ListRiskRulesRequest) (*ListRiskRulesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRiskRules not implemented")
}
func (UnimplementedRiskServiceServer) GetRiskRule(context.Context, *GetRiskRuleRequest) (*GetRiskRuleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRiskRule not implemented")
}
func (UnimplementedRiskServiceServer) UpdateRiskRule(context.Context, *UpdateRiskRuleRequest) (*UpdateRiskRuleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateRiskRule not implemented")
}
func (UnimplementedRiskServiceServer) GetRateLimitStatus(context.Context, *GetRateLimitStatusRequest) (*GetRateLimitStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRateLimitStatus not implemented")
}
func (UnimplementedRiskServiceServer) ResetRateLimit(context.Context, *ResetRateLimitRequest) (*ResetRateLimitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResetRateLimit not implemented")
}
func (UnimplementedRiskServiceServer) ListRiskEvents(context.Context, *ListRiskEventsRequest) (*ListRiskEventsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRiskEvents not implemented")
}
func (UnimplementedRiskServiceServer) GetRiskEvent(context.Context, *GetRiskEventRequest) (*GetRiskEventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRiskEvent not implemented")
}
func (UnimplementedRiskServiceServer) AcknowledgeRiskEvent(context.Context, *AcknowledgeRiskEventRequest) (*AcknowledgeRiskEventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AcknowledgeRiskEvent not implemented")
}
func (UnimplementedRiskServiceServer) GetUserLimits(context.Context, *GetUserLimitsRequest) (*GetUserLimitsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserLimits not implemented")
}
func (UnimplementedRiskServiceServer) SetUserLimits(context.Context, *SetUserLimitsRequest) (*SetUserLimitsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetUserLimits not implemented")
}
func (UnimplementedRiskServiceServer) FreezeAccount(context.Context, *FreezeAccountRequest) (*FreezeAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FreezeAccount not implemented")
}
func (UnimplementedRiskServiceServer) UnfreezeAccount(context.Context, *UnfreezeAccountRequest) (*UnfreezeAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnfreezeAccount not implemented")
}
func (UnimplementedRiskServiceServer) GetAccountStatus(context.Context, *GetAccountStatusRequest) (*GetAccountStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAccountStatus not implemented")
}
func (UnimplementedRiskServiceServer) GetRiskStats(context.Context, *GetRiskStatsRequest) (*GetRiskStatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRiskStats not implemented")
}
func (UnimplementedRiskServiceServer) ListWithdrawalReviews(context.Context, *ListWithdrawalReviewsRequest) (*ListWithdrawalReviewsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListWithdrawalReviews not implemented")
}
func (UnimplementedRiskServiceServer) GetWithdrawalReview(context.Context, *GetWithdrawalReviewRequest) (*GetWithdrawalReviewResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWithdrawalReview not implemented")
}
func (UnimplementedRiskServiceServer) ApproveWithdrawalReview(context.Context, *ApproveWithdrawalReviewRequest) (*ApproveWithdrawalReviewResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApproveWithdrawalReview not implemented")
}
func (UnimplementedRiskServiceServer) RejectWithdrawalReview(context.Context, *RejectWithdrawalReviewRequest) (*RejectWithdrawalReviewResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RejectWithdrawalReview not implemented")
}
func (UnimplementedRiskServiceServer) GetWithdrawalReviewStats(context.Context, *GetWithdrawalReviewStatsRequest) (*GetWithdrawalReviewStatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWithdrawalReviewStats not implemented")
}
func (UnimplementedRiskServiceServer) mustEmbedUnimplementedRiskServiceServer() {}
func (UnimplementedRiskServiceServer) testEmbeddedByValue()                     {}

// UnsafeRiskServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RiskServiceServer will
// result in compilation errors.
type UnsafeRiskServiceServer interface {
	mustEmbedUnimplementedRiskServiceServer()
}

func RegisterRiskServiceServer(s grpc.ServiceRegistrar, srv RiskServiceServer) {
	// If the following call pancis, it indicates UnimplementedRiskServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RiskService_ServiceDesc, srv)
}

func _RiskService_CheckOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiskServiceServer).CheckOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RiskService_CheckOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiskServiceServer).CheckOrder(ctx, req.(*CheckOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RiskService_CheckWithdrawal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckWithdrawalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiskServiceServer).CheckWithdrawal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RiskService_CheckWithdrawal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiskServiceServer).CheckWithdrawal(ctx, req.(*CheckWithdrawalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RiskService_CheckTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiskServiceServer).CheckTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RiskService_CheckTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiskServiceServer).CheckTransaction(ctx, req.(*CheckTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RiskService_AddToBlacklist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddToBlacklistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiskServiceServer).AddToBlacklist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RiskService_AddToBlacklist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiskServiceServer).AddToBlacklist(ctx, req.(*AddToBlacklistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RiskService_RemoveFromBlacklist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveFromBlacklistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiskServiceServer).RemoveFromBlacklist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RiskService_RemoveFromBlacklist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiskServiceServer).RemoveFromBlacklist(ctx, req.(*RemoveFromBlacklistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RiskService_CheckBlacklist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckBlacklistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiskServiceServer).CheckBlacklist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RiskService_CheckBlacklist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiskServiceServer).CheckBlacklist(ctx, req.(*CheckBlacklistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RiskService_ListBlacklist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBlacklistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiskServiceServer).ListBlacklist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RiskService_ListBlacklist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiskServiceServer).ListBlacklist(ctx, req.(*ListBlacklistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RiskService_ListRiskRules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRiskRulesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiskServiceServer).ListRiskRules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RiskService_ListRiskRules_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiskServiceServer).ListRiskRules(ctx, req.(*ListRiskRulesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RiskService_GetRiskRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRiskRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiskServiceServer).GetRiskRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RiskService_GetRiskRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiskServiceServer).GetRiskRule(ctx, req.(*GetRiskRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RiskService_UpdateRiskRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRiskRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiskServiceServer).UpdateRiskRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RiskService_UpdateRiskRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiskServiceServer).UpdateRiskRule(ctx, req.(*UpdateRiskRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RiskService_GetRateLimitStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRateLimitStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiskServiceServer).GetRateLimitStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RiskService_GetRateLimitStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiskServiceServer).GetRateLimitStatus(ctx, req.(*GetRateLimitStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RiskService_ResetRateLimit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetRateLimitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiskServiceServer).ResetRateLimit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RiskService_ResetRateLimit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiskServiceServer).ResetRateLimit(ctx, req.(*ResetRateLimitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RiskService_ListRiskEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRiskEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiskServiceServer).ListRiskEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RiskService_ListRiskEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiskServiceServer).ListRiskEvents(ctx, req.(*ListRiskEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RiskService_GetRiskEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRiskEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiskServiceServer).GetRiskEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RiskService_GetRiskEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiskServiceServer).GetRiskEvent(ctx, req.(*GetRiskEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RiskService_AcknowledgeRiskEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcknowledgeRiskEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiskServiceServer).AcknowledgeRiskEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RiskService_AcknowledgeRiskEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiskServiceServer).AcknowledgeRiskEvent(ctx, req.(*AcknowledgeRiskEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RiskService_GetUserLimits_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserLimitsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiskServiceServer).GetUserLimits(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RiskService_GetUserLimits_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiskServiceServer).GetUserLimits(ctx, req.(*GetUserLimitsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RiskService_SetUserLimits_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetUserLimitsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiskServiceServer).SetUserLimits(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RiskService_SetUserLimits_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiskServiceServer).SetUserLimits(ctx, req.(*SetUserLimitsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RiskService_FreezeAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FreezeAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiskServiceServer).FreezeAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RiskService_FreezeAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiskServiceServer).FreezeAccount(ctx, req.(*FreezeAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RiskService_UnfreezeAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnfreezeAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiskServiceServer).UnfreezeAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RiskService_UnfreezeAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiskServiceServer).UnfreezeAccount(ctx, req.(*UnfreezeAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RiskService_GetAccountStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAccountStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiskServiceServer).GetAccountStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RiskService_GetAccountStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiskServiceServer).GetAccountStatus(ctx, req.(*GetAccountStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RiskService_GetRiskStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRiskStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiskServiceServer).GetRiskStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RiskService_GetRiskStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiskServiceServer).GetRiskStats(ctx, req.(*GetRiskStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RiskService_ListWithdrawalReviews_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWithdrawalReviewsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiskServiceServer).ListWithdrawalReviews(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RiskService_ListWithdrawalReviews_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiskServiceServer).ListWithdrawalReviews(ctx, req.(*ListWithdrawalReviewsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RiskService_GetWithdrawalReview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWithdrawalReviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiskServiceServer).GetWithdrawalReview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RiskService_GetWithdrawalReview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiskServiceServer).GetWithdrawalReview(ctx, req.(*GetWithdrawalReviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RiskService_ApproveWithdrawalReview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApproveWithdrawalReviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiskServiceServer).ApproveWithdrawalReview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RiskService_ApproveWithdrawalReview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiskServiceServer).ApproveWithdrawalReview(ctx, req.(*ApproveWithdrawalReviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RiskService_RejectWithdrawalReview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RejectWithdrawalReviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiskServiceServer).RejectWithdrawalReview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RiskService_RejectWithdrawalReview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiskServiceServer).RejectWithdrawalReview(ctx, req.(*RejectWithdrawalReviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RiskService_GetWithdrawalReviewStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWithdrawalReviewStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiskServiceServer).GetWithdrawalReviewStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RiskService_GetWithdrawalReviewStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiskServiceServer).GetWithdrawalReviewStats(ctx, req.(*GetWithdrawalReviewStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RiskService_ServiceDesc is the grpc.ServiceDesc for RiskService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RiskService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "eidos.risk.v1.RiskService",
	HandlerType: (*RiskServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckOrder",
			Handler:    _RiskService_CheckOrder_Handler,
		},
		{
			MethodName: "CheckWithdrawal",
			Handler:    _RiskService_CheckWithdrawal_Handler,
		},
		{
			MethodName: "CheckTransaction",
			Handler:    _RiskService_CheckTransaction_Handler,
		},
		{
			MethodName: "AddToBlacklist",
			Handler:    _RiskService_AddToBlacklist_Handler,
		},
		{
			MethodName: "RemoveFromBlacklist",
			Handler:    _RiskService_RemoveFromBlacklist_Handler,
		},
		{
			MethodName: "CheckBlacklist",
			Handler:    _RiskService_CheckBlacklist_Handler,
		},
		{
			MethodName: "ListBlacklist",
			Handler:    _RiskService_ListBlacklist_Handler,
		},
		{
			MethodName: "ListRiskRules",
			Handler:    _RiskService_ListRiskRules_Handler,
		},
		{
			MethodName: "GetRiskRule",
			Handler:    _RiskService_GetRiskRule_Handler,
		},
		{
			MethodName: "UpdateRiskRule",
			Handler:    _RiskService_UpdateRiskRule_Handler,
		},
		{
			MethodName: "GetRateLimitStatus",
			Handler:    _RiskService_GetRateLimitStatus_Handler,
		},
		{
			MethodName: "ResetRateLimit",
			Handler:    _RiskService_ResetRateLimit_Handler,
		},
		{
			MethodName: "ListRiskEvents",
			Handler:    _RiskService_ListRiskEvents_Handler,
		},
		{
			MethodName: "GetRiskEvent",
			Handler:    _RiskService_GetRiskEvent_Handler,
		},
		{
			MethodName: "AcknowledgeRiskEvent",
			Handler:    _RiskService_AcknowledgeRiskEvent_Handler,
		},
		{
			MethodName: "GetUserLimits",
			Handler:    _RiskService_GetUserLimits_Handler,
		},
		{
			MethodName: "SetUserLimits",
			Handler:    _RiskService_SetUserLimits_Handler,
		},
		{
			MethodName: "FreezeAccount",
			Handler:    _RiskService_FreezeAccount_Handler,
		},
		{
			MethodName: "UnfreezeAccount",
			Handler:    _RiskService_UnfreezeAccount_Handler,
		},
		{
			MethodName: "GetAccountStatus",
			Handler:    _RiskService_GetAccountStatus_Handler,
		},
		{
			MethodName: "GetRiskStats",
			Handler:    _RiskService_GetRiskStats_Handler,
		},
		{
			MethodName: "ListWithdrawalReviews",
			Handler:    _RiskService_ListWithdrawalReviews_Handler,
		},
		{
			MethodName: "GetWithdrawalReview",
			Handler:    _RiskService_GetWithdrawalReview_Handler,
		},
		{
			MethodName: "ApproveWithdrawalReview",
			Handler:    _RiskService_ApproveWithdrawalReview_Handler,
		},
		{
			MethodName: "RejectWithdrawalReview",
			Handler:    _RiskService_RejectWithdrawalReview_Handler,
		},
		{
			MethodName: "GetWithdrawalReviewStats",
			Handler:    _RiskService_GetWithdrawalReviewStats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "risk/v1/risk.proto",
}
