// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: matching/v1/matching.proto

package matchingv1

import (
	v1 "github.com/eidos-exchange/eidos/proto/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetOrderbookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Market        string                 `protobuf:"bytes,1,opt,name=market,proto3" json:"market,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"` // 每边数量限制，默认 100
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderbookRequest) Reset() {
	*x = GetOrderbookRequest{}
	mi := &file_matching_v1_matching_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderbookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderbookRequest) ProtoMessage() {}

func (x *GetOrderbookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_matching_v1_matching_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderbookRequest.ProtoReflect.Descriptor instead.
func (*GetOrderbookRequest) Descriptor() ([]byte, []int) {
	return file_matching_v1_matching_proto_rawDescGZIP(), []int{0}
}

func (x *GetOrderbookRequest) GetMarket() string {
	if x != nil {
		return x.Market
	}
	return ""
}

func (x *GetOrderbookRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetOrderbookResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Market        string                 `protobuf:"bytes,1,opt,name=market,proto3" json:"market,omitempty"`
	Bids          []*PriceLevel          `protobuf:"bytes,2,rep,name=bids,proto3" json:"bids,omitempty"`
	Asks          []*PriceLevel          `protobuf:"bytes,3,rep,name=asks,proto3" json:"asks,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Sequence      uint64                 `protobuf:"varint,5,opt,name=sequence,proto3" json:"sequence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderbookResponse) Reset() {
	*x = GetOrderbookResponse{}
	mi := &file_matching_v1_matching_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderbookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderbookResponse) ProtoMessage() {}

func (x *GetOrderbookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_matching_v1_matching_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderbookResponse.ProtoReflect.Descriptor instead.
func (*GetOrderbookResponse) Descriptor() ([]byte, []int) {
	return file_matching_v1_matching_proto_rawDescGZIP(), []int{1}
}

func (x *GetOrderbookResponse) GetMarket() string {
	if x != nil {
		return x.Market
	}
	return ""
}

func (x *GetOrderbookResponse) GetBids() []*PriceLevel {
	if x != nil {
		return x.Bids
	}
	return nil
}

func (x *GetOrderbookResponse) GetAsks() []*PriceLevel {
	if x != nil {
		return x.Asks
	}
	return nil
}

func (x *GetOrderbookResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *GetOrderbookResponse) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

type GetDepthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Market        string                 `protobuf:"bytes,1,opt,name=market,proto3" json:"market,omitempty"`
	Level         int32                  `protobuf:"varint,2,opt,name=level,proto3" json:"level,omitempty"` // 5, 10, 20, 50, 100
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDepthRequest) Reset() {
	*x = GetDepthRequest{}
	mi := &file_matching_v1_matching_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDepthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDepthRequest) ProtoMessage() {}

func (x *GetDepthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_matching_v1_matching_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDepthRequest.ProtoReflect.Descriptor instead.
func (*GetDepthRequest) Descriptor() ([]byte, []int) {
	return file_matching_v1_matching_proto_rawDescGZIP(), []int{2}
}

func (x *GetDepthRequest) GetMarket() string {
	if x != nil {
		return x.Market
	}
	return ""
}

func (x *GetDepthRequest) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

type GetDepthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Market        string                 `protobuf:"bytes,1,opt,name=market,proto3" json:"market,omitempty"`
	Bids          []*PriceLevel          `protobuf:"bytes,2,rep,name=bids,proto3" json:"bids,omitempty"`
	Asks          []*PriceLevel          `protobuf:"bytes,3,rep,name=asks,proto3" json:"asks,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDepthResponse) Reset() {
	*x = GetDepthResponse{}
	mi := &file_matching_v1_matching_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDepthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDepthResponse) ProtoMessage() {}

func (x *GetDepthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_matching_v1_matching_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDepthResponse.ProtoReflect.Descriptor instead.
func (*GetDepthResponse) Descriptor() ([]byte, []int) {
	return file_matching_v1_matching_proto_rawDescGZIP(), []int{3}
}

func (x *GetDepthResponse) GetMarket() string {
	if x != nil {
		return x.Market
	}
	return ""
}

func (x *GetDepthResponse) GetBids() []*PriceLevel {
	if x != nil {
		return x.Bids
	}
	return nil
}

func (x *GetDepthResponse) GetAsks() []*PriceLevel {
	if x != nil {
		return x.Asks
	}
	return nil
}

func (x *GetDepthResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type PriceLevel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Price         string                 `protobuf:"bytes,1,opt,name=price,proto3" json:"price,omitempty"`
	Amount        string                 `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	OrderCount    int32                  `protobuf:"varint,3,opt,name=order_count,json=orderCount,proto3" json:"order_count,omitempty"` // 该价位订单数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PriceLevel) Reset() {
	*x = PriceLevel{}
	mi := &file_matching_v1_matching_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PriceLevel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriceLevel) ProtoMessage() {}

func (x *PriceLevel) ProtoReflect() protoreflect.Message {
	mi := &file_matching_v1_matching_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriceLevel.ProtoReflect.Descriptor instead.
func (*PriceLevel) Descriptor() ([]byte, []int) {
	return file_matching_v1_matching_proto_rawDescGZIP(), []int{4}
}

func (x *PriceLevel) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *PriceLevel) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *PriceLevel) GetOrderCount() int32 {
	if x != nil {
		return x.OrderCount
	}
	return 0
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_matching_v1_matching_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_matching_v1_matching_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_matching_v1_matching_proto_rawDescGZIP(), []int{5}
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Healthy       bool                     `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Markets       map[string]*MarketStatus `protobuf:"bytes,2,rep,name=markets,proto3" json:"markets,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_matching_v1_matching_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_matching_v1_matching_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_matching_v1_matching_proto_rawDescGZIP(), []int{6}
}

func (x *HealthCheckResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthCheckResponse) GetMarkets() map[string]*MarketStatus {
	if x != nil {
		return x.Markets
	}
	return nil
}

type MarketStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Market        string                 `protobuf:"bytes,1,opt,name=market,proto3" json:"market,omitempty"`
	Active        bool                   `protobuf:"varint,2,opt,name=active,proto3" json:"active,omitempty"`
	BidCount      int64                  `protobuf:"varint,3,opt,name=bid_count,json=bidCount,proto3" json:"bid_count,omitempty"`
	AskCount      int64                  `protobuf:"varint,4,opt,name=ask_count,json=askCount,proto3" json:"ask_count,omitempty"`
	BestBid       string                 `protobuf:"bytes,5,opt,name=best_bid,json=bestBid,proto3" json:"best_bid,omitempty"`
	BestAsk       string                 `protobuf:"bytes,6,opt,name=best_ask,json=bestAsk,proto3" json:"best_ask,omitempty"`
	LastMatchTime int64                  `protobuf:"varint,7,opt,name=last_match_time,json=lastMatchTime,proto3" json:"last_match_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarketStatus) Reset() {
	*x = MarketStatus{}
	mi := &file_matching_v1_matching_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarketStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketStatus) ProtoMessage() {}

func (x *MarketStatus) ProtoReflect() protoreflect.Message {
	mi := &file_matching_v1_matching_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketStatus.ProtoReflect.Descriptor instead.
func (*MarketStatus) Descriptor() ([]byte, []int) {
	return file_matching_v1_matching_proto_rawDescGZIP(), []int{7}
}

func (x *MarketStatus) GetMarket() string {
	if x != nil {
		return x.Market
	}
	return ""
}

func (x *MarketStatus) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *MarketStatus) GetBidCount() int64 {
	if x != nil {
		return x.BidCount
	}
	return 0
}

func (x *MarketStatus) GetAskCount() int64 {
	if x != nil {
		return x.AskCount
	}
	return 0
}

func (x *MarketStatus) GetBestBid() string {
	if x != nil {
		return x.BestBid
	}
	return ""
}

func (x *MarketStatus) GetBestAsk() string {
	if x != nil {
		return x.BestAsk
	}
	return ""
}

func (x *MarketStatus) GetLastMatchTime() int64 {
	if x != nil {
		return x.LastMatchTime
	}
	return 0
}

// 订单消息 (Kafka: orders)
type OrderMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Wallet        string                 `protobuf:"bytes,2,opt,name=wallet,proto3" json:"wallet,omitempty"`
	Market        string                 `protobuf:"bytes,3,opt,name=market,proto3" json:"market,omitempty"`
	Side          v1.OrderSide           `protobuf:"varint,4,opt,name=side,proto3,enum=eidos.common.v1.OrderSide" json:"side,omitempty"`
	OrderType     v1.OrderType           `protobuf:"varint,5,opt,name=order_type,json=orderType,proto3,enum=eidos.common.v1.OrderType" json:"order_type,omitempty"`
	Price         string                 `protobuf:"bytes,6,opt,name=price,proto3" json:"price,omitempty"`
	Amount        string                 `protobuf:"bytes,7,opt,name=amount,proto3" json:"amount,omitempty"`
	TimeInForce   v1.TimeInForce         `protobuf:"varint,8,opt,name=time_in_force,json=timeInForce,proto3,enum=eidos.common.v1.TimeInForce" json:"time_in_force,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderMessage) Reset() {
	*x = OrderMessage{}
	mi := &file_matching_v1_matching_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderMessage) ProtoMessage() {}

func (x *OrderMessage) ProtoReflect() protoreflect.Message {
	mi := &file_matching_v1_matching_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderMessage.ProtoReflect.Descriptor instead.
func (*OrderMessage) Descriptor() ([]byte, []int) {
	return file_matching_v1_matching_proto_rawDescGZIP(), []int{8}
}

func (x *OrderMessage) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *OrderMessage) GetWallet() string {
	if x != nil {
		return x.Wallet
	}
	return ""
}

func (x *OrderMessage) GetMarket() string {
	if x != nil {
		return x.Market
	}
	return ""
}

func (x *OrderMessage) GetSide() v1.OrderSide {
	if x != nil {
		return x.Side
	}
	return v1.OrderSide(0)
}

func (x *OrderMessage) GetOrderType() v1.OrderType {
	if x != nil {
		return x.OrderType
	}
	return v1.OrderType(0)
}

func (x *OrderMessage) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *OrderMessage) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *OrderMessage) GetTimeInForce() v1.TimeInForce {
	if x != nil {
		return x.TimeInForce
	}
	return v1.TimeInForce(0)
}

func (x *OrderMessage) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

// 取消请求消息 (Kafka: cancel-requests)
type CancelRequestMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Market        string                 `protobuf:"bytes,2,opt,name=market,proto3" json:"market,omitempty"`
	Wallet        string                 `protobuf:"bytes,3,opt,name=wallet,proto3" json:"wallet,omitempty"`
	RequestedAt   int64                  `protobuf:"varint,4,opt,name=requested_at,json=requestedAt,proto3" json:"requested_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelRequestMessage) Reset() {
	*x = CancelRequestMessage{}
	mi := &file_matching_v1_matching_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRequestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRequestMessage) ProtoMessage() {}

func (x *CancelRequestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_matching_v1_matching_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRequestMessage.ProtoReflect.Descriptor instead.
func (*CancelRequestMessage) Descriptor() ([]byte, []int) {
	return file_matching_v1_matching_proto_rawDescGZIP(), []int{9}
}

func (x *CancelRequestMessage) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *CancelRequestMessage) GetMarket() string {
	if x != nil {
		return x.Market
	}
	return ""
}

func (x *CancelRequestMessage) GetWallet() string {
	if x != nil {
		return x.Wallet
	}
	return ""
}

func (x *CancelRequestMessage) GetRequestedAt() int64 {
	if x != nil {
		return x.RequestedAt
	}
	return 0
}

// 成交结果消息 (Kafka: trade-results)
type TradeResultMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TradeId       string                 `protobuf:"bytes,1,opt,name=trade_id,json=tradeId,proto3" json:"trade_id,omitempty"`
	Market        string                 `protobuf:"bytes,2,opt,name=market,proto3" json:"market,omitempty"`
	MakerOrderId  string                 `protobuf:"bytes,3,opt,name=maker_order_id,json=makerOrderId,proto3" json:"maker_order_id,omitempty"`
	TakerOrderId  string                 `protobuf:"bytes,4,opt,name=taker_order_id,json=takerOrderId,proto3" json:"taker_order_id,omitempty"`
	MakerWallet   string                 `protobuf:"bytes,5,opt,name=maker_wallet,json=makerWallet,proto3" json:"maker_wallet,omitempty"`
	TakerWallet   string                 `protobuf:"bytes,6,opt,name=taker_wallet,json=takerWallet,proto3" json:"taker_wallet,omitempty"`
	TakerSide     v1.OrderSide           `protobuf:"varint,7,opt,name=taker_side,json=takerSide,proto3,enum=eidos.common.v1.OrderSide" json:"taker_side,omitempty"`
	Price         string                 `protobuf:"bytes,8,opt,name=price,proto3" json:"price,omitempty"`
	Amount        string                 `protobuf:"bytes,9,opt,name=amount,proto3" json:"amount,omitempty"`
	QuoteAmount   string                 `protobuf:"bytes,10,opt,name=quote_amount,json=quoteAmount,proto3" json:"quote_amount,omitempty"`
	MakerFee      string                 `protobuf:"bytes,11,opt,name=maker_fee,json=makerFee,proto3" json:"maker_fee,omitempty"`
	TakerFee      string                 `protobuf:"bytes,12,opt,name=taker_fee,json=takerFee,proto3" json:"taker_fee,omitempty"`
	MatchedAt     int64                  `protobuf:"varint,13,opt,name=matched_at,json=matchedAt,proto3" json:"matched_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TradeResultMessage) Reset() {
	*x = TradeResultMessage{}
	mi := &file_matching_v1_matching_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TradeResultMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TradeResultMessage) ProtoMessage() {}

func (x *TradeResultMessage) ProtoReflect() protoreflect.Message {
	mi := &file_matching_v1_matching_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TradeResultMessage.ProtoReflect.Descriptor instead.
func (*TradeResultMessage) Descriptor() ([]byte, []int) {
	return file_matching_v1_matching_proto_rawDescGZIP(), []int{10}
}

func (x *TradeResultMessage) GetTradeId() string {
	if x != nil {
		return x.TradeId
	}
	return ""
}

func (x *TradeResultMessage) GetMarket() string {
	if x != nil {
		return x.Market
	}
	return ""
}

func (x *TradeResultMessage) GetMakerOrderId() string {
	if x != nil {
		return x.MakerOrderId
	}
	return ""
}

func (x *TradeResultMessage) GetTakerOrderId() string {
	if x != nil {
		return x.TakerOrderId
	}
	return ""
}

func (x *TradeResultMessage) GetMakerWallet() string {
	if x != nil {
		return x.MakerWallet
	}
	return ""
}

func (x *TradeResultMessage) GetTakerWallet() string {
	if x != nil {
		return x.TakerWallet
	}
	return ""
}

func (x *TradeResultMessage) GetTakerSide() v1.OrderSide {
	if x != nil {
		return x.TakerSide
	}
	return v1.OrderSide(0)
}

func (x *TradeResultMessage) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *TradeResultMessage) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *TradeResultMessage) GetQuoteAmount() string {
	if x != nil {
		return x.QuoteAmount
	}
	return ""
}

func (x *TradeResultMessage) GetMakerFee() string {
	if x != nil {
		return x.MakerFee
	}
	return ""
}

func (x *TradeResultMessage) GetTakerFee() string {
	if x != nil {
		return x.TakerFee
	}
	return ""
}

func (x *TradeResultMessage) GetMatchedAt() int64 {
	if x != nil {
		return x.MatchedAt
	}
	return 0
}

// 订单簿更新消息 (Kafka: orderbook-updates)
type OrderbookUpdateMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Market        string                 `protobuf:"bytes,1,opt,name=market,proto3" json:"market,omitempty"`
	Sequence      uint64                 `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Bids          []*PriceLevelUpdate    `protobuf:"bytes,3,rep,name=bids,proto3" json:"bids,omitempty"`
	Asks          []*PriceLevelUpdate    `protobuf:"bytes,4,rep,name=asks,proto3" json:"asks,omitempty"`
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderbookUpdateMessage) Reset() {
	*x = OrderbookUpdateMessage{}
	mi := &file_matching_v1_matching_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderbookUpdateMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderbookUpdateMessage) ProtoMessage() {}

func (x *OrderbookUpdateMessage) ProtoReflect() protoreflect.Message {
	mi := &file_matching_v1_matching_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderbookUpdateMessage.ProtoReflect.Descriptor instead.
func (*OrderbookUpdateMessage) Descriptor() ([]byte, []int) {
	return file_matching_v1_matching_proto_rawDescGZIP(), []int{11}
}

func (x *OrderbookUpdateMessage) GetMarket() string {
	if x != nil {
		return x.Market
	}
	return ""
}

func (x *OrderbookUpdateMessage) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *OrderbookUpdateMessage) GetBids() []*PriceLevelUpdate {
	if x != nil {
		return x.Bids
	}
	return nil
}

func (x *OrderbookUpdateMessage) GetAsks() []*PriceLevelUpdate {
	if x != nil {
		return x.Asks
	}
	return nil
}

func (x *OrderbookUpdateMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type PriceLevelUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Price         string                 `protobuf:"bytes,1,opt,name=price,proto3" json:"price,omitempty"`
	Amount        string                 `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"` // 0 表示删除该价位
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PriceLevelUpdate) Reset() {
	*x = PriceLevelUpdate{}
	mi := &file_matching_v1_matching_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PriceLevelUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriceLevelUpdate) ProtoMessage() {}

func (x *PriceLevelUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_matching_v1_matching_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriceLevelUpdate.ProtoReflect.Descriptor instead.
func (*PriceLevelUpdate) Descriptor() ([]byte, []int) {
	return file_matching_v1_matching_proto_rawDescGZIP(), []int{12}
}

func (x *PriceLevelUpdate) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *PriceLevelUpdate) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

// 订单取消确认消息 (Kafka: order-cancelled)
type OrderCancelledMessage struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	OrderId         string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Market          string                 `protobuf:"bytes,2,opt,name=market,proto3" json:"market,omitempty"`
	Wallet          string                 `protobuf:"bytes,3,opt,name=wallet,proto3" json:"wallet,omitempty"`
	RemainingAmount string                 `protobuf:"bytes,4,opt,name=remaining_amount,json=remainingAmount,proto3" json:"remaining_amount,omitempty"`
	CancelledAt     int64                  `protobuf:"varint,5,opt,name=cancelled_at,json=cancelledAt,proto3" json:"cancelled_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *OrderCancelledMessage) Reset() {
	*x = OrderCancelledMessage{}
	mi := &file_matching_v1_matching_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderCancelledMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderCancelledMessage) ProtoMessage() {}

func (x *OrderCancelledMessage) ProtoReflect() protoreflect.Message {
	mi := &file_matching_v1_matching_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderCancelledMessage.ProtoReflect.Descriptor instead.
func (*OrderCancelledMessage) Descriptor() ([]byte, []int) {
	return file_matching_v1_matching_proto_rawDescGZIP(), []int{13}
}

func (x *OrderCancelledMessage) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *OrderCancelledMessage) GetMarket() string {
	if x != nil {
		return x.Market
	}
	return ""
}

func (x *OrderCancelledMessage) GetWallet() string {
	if x != nil {
		return x.Wallet
	}
	return ""
}

func (x *OrderCancelledMessage) GetRemainingAmount() string {
	if x != nil {
		return x.RemainingAmount
	}
	return ""
}

func (x *OrderCancelledMessage) GetCancelledAt() int64 {
	if x != nil {
		return x.CancelledAt
	}
	return 0
}

var File_matching_v1_matching_proto protoreflect.FileDescriptor

const file_matching_v1_matching_proto_rawDesc = "" +
	"\n" +
	"\x1amatching/v1/matching.proto\x12\x11eidos.matching.v1\x1a\x12common/enums.proto\"C\n" +
	"\x13GetOrderbookRequest\x12\x16\n" +
	"\x06market\x18\x01 \x01(\tR\x06market\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"\xce\x01\n" +
	"\x14GetOrderbookResponse\x12\x16\n" +
	"\x06market\x18\x01 \x01(\tR\x06market\x121\n" +
	"\x04bids\x18\x02 \x03(\v2\x1d.eidos.matching.v1.PriceLevelR\x04bids\x121\n" +
	"\x04asks\x18\x03 \x03(\v2\x1d.eidos.matching.v1.PriceLevelR\x04asks\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x12\x1a\n" +
	"\bsequence\x18\x05 \x01(\x04R\bsequence\"?\n" +
	"\x0fGetDepthRequest\x12\x16\n" +
	"\x06market\x18\x01 \x01(\tR\x06market\x12\x14\n" +
	"\x05level\x18\x02 \x01(\x05R\x05level\"\xae\x01\n" +
	"\x10GetDepthResponse\x12\x16\n" +
	"\x06market\x18\x01 \x01(\tR\x06market\x121\n" +
	"\x04bids\x18\x02 \x03(\v2\x1d.eidos.matching.v1.PriceLevelR\x04bids\x121\n" +
	"\x04asks\x18\x03 \x03(\v2\x1d.eidos.matching.v1.PriceLevelR\x04asks\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"[\n" +
	"\n" +
	"PriceLevel\x12\x14\n" +
	"\x05price\x18\x01 \x01(\tR\x05price\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\tR\x06amount\x12\x1f\n" +
	"\vorder_count\x18\x03 \x01(\x05R\n" +
	"orderCount\"\x14\n" +
	"\x12HealthCheckRequest\"\xdb\x01\n" +
	"\x13HealthCheckResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12M\n" +
	"\amarkets\x18\x02 \x03(\v23.eidos.matching.v1.HealthCheckResponse.MarketsEntryR\amarkets\x1a[\n" +
	"\fMarketsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x125\n" +
	"\x05value\x18\x02 \x01(\v2\x1f.eidos.matching.v1.MarketStatusR\x05value:\x028\x01\"\xd6\x01\n" +
	"\fMarketStatus\x12\x16\n" +
	"\x06market\x18\x01 \x01(\tR\x06market\x12\x16\n" +
	"\x06active\x18\x02 \x01(\bR\x06active\x12\x1b\n" +
	"\tbid_count\x18\x03 \x01(\x03R\bbidCount\x12\x1b\n" +
	"\task_count\x18\x04 \x01(\x03R\baskCount\x12\x19\n" +
	"\bbest_bid\x18\x05 \x01(\tR\abestBid\x12\x19\n" +
	"\bbest_ask\x18\x06 \x01(\tR\abestAsk\x12&\n" +
	"\x0flast_match_time\x18\a \x01(\x03R\rlastMatchTime\"\xd3\x02\n" +
	"\fOrderMessage\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x16\n" +
	"\x06wallet\x18\x02 \x01(\tR\x06wallet\x12\x16\n" +
	"\x06market\x18\x03 \x01(\tR\x06market\x12.\n" +
	"\x04side\x18\x04 \x01(\x0e2\x1a.eidos.common.v1.OrderSideR\x04side\x129\n" +
	"\n" +
	"order_type\x18\x05 \x01(\x0e2\x1a.eidos.common.v1.OrderTypeR\torderType\x12\x14\n" +
	"\x05price\x18\x06 \x01(\tR\x05price\x12\x16\n" +
	"\x06amount\x18\a \x01(\tR\x06amount\x12@\n" +
	"\rtime_in_force\x18\b \x01(\x0e2\x1c.eidos.common.v1.TimeInForceR\vtimeInForce\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\x03R\tcreatedAt\"\x84\x01\n" +
	"\x14CancelRequestMessage\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x16\n" +
	"\x06market\x18\x02 \x01(\tR\x06market\x12\x16\n" +
	"\x06wallet\x18\x03 \x01(\tR\x06wallet\x12!\n" +
	"\frequested_at\x18\x04 \x01(\x03R\vrequestedAt\"\xbe\x03\n" +
	"\x12TradeResultMessage\x12\x19\n" +
	"\btrade_id\x18\x01 \x01(\tR\atradeId\x12\x16\n" +
	"\x06market\x18\x02 \x01(\tR\x06market\x12$\n" +
	"\x0emaker_order_id\x18\x03 \x01(\tR\fmakerOrderId\x12$\n" +
	"\x0etaker_order_id\x18\x04 \x01(\tR\ftakerOrderId\x12!\n" +
	"\fmaker_wallet\x18\x05 \x01(\tR\vmakerWallet\x12!\n" +
	"\ftaker_wallet\x18\x06 \x01(\tR\vtakerWallet\x129\n" +
	"\n" +
	"taker_side\x18\a \x01(\x0e2\x1a.eidos.common.v1.OrderSideR\ttakerSide\x12\x14\n" +
	"\x05price\x18\b \x01(\tR\x05price\x12\x16\n" +
	"\x06amount\x18\t \x01(\tR\x06amount\x12!\n" +
	"\fquote_amount\x18\n" +
	" \x01(\tR\vquoteAmount\x12\x1b\n" +
	"\tmaker_fee\x18\v \x01(\tR\bmakerFee\x12\x1b\n" +
	"\ttaker_fee\x18\f \x01(\tR\btakerFee\x12\x1d\n" +
	"\n" +
	"matched_at\x18\r \x01(\x03R\tmatchedAt\"\xdc\x01\n" +
	"\x16OrderbookUpdateMessage\x12\x16\n" +
	"\x06market\x18\x01 \x01(\tR\x06market\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\x04R\bsequence\x127\n" +
	"\x04bids\x18\x03 \x03(\v2#.eidos.matching.v1.PriceLevelUpdateR\x04bids\x127\n" +
	"\x04asks\x18\x04 \x03(\v2#.eidos.matching.v1.PriceLevelUpdateR\x04asks\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\"@\n" +
	"\x10PriceLevelUpdate\x12\x14\n" +
	"\x05price\x18\x01 \x01(\tR\x05price\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\tR\x06amount\"\xb0\x01\n" +
	"\x15OrderCancelledMessage\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x16\n" +
	"\x06market\x18\x02 \x01(\tR\x06market\x12\x16\n" +
	"\x06wallet\x18\x03 \x01(\tR\x06wallet\x12)\n" +
	"\x10remaining_amount\x18\x04 \x01(\tR\x0fremainingAmount\x12!\n" +
	"\fcancelled_at\x18\x05 \x01(\x03R\vcancelledAt2\xa5\x02\n" +
	"\x0fMatchingService\x12_\n" +
	"\fGetOrderbook\x12&.eidos.matching.v1.GetOrderbookRequest\x1a'.eidos.matching.v1.GetOrderbookResponse\x12S\n" +
	"\bGetDepth\x12\".eidos.matching.v1.GetDepthRequest\x1a#.eidos.matching.v1.GetDepthResponse\x12\\\n" +
	"\vHealthCheck\x12%.eidos.matching.v1.HealthCheckRequest\x1a&.eidos.matching.v1.HealthCheckResponseB>Z<github.com/eidos-exchange/eidos/proto/matching/v1;matchingv1b\x06proto3"

var (
	file_matching_v1_matching_proto_rawDescOnce sync.Once
	file_matching_v1_matching_proto_rawDescData []byte
)

func file_matching_v1_matching_proto_rawDescGZIP() []byte {
	file_matching_v1_matching_proto_rawDescOnce.Do(func() {
		file_matching_v1_matching_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_matching_v1_matching_proto_rawDesc), len(file_matching_v1_matching_proto_rawDesc)))
	})
	return file_matching_v1_matching_proto_rawDescData
}

var file_matching_v1_matching_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_matching_v1_matching_proto_goTypes = []any{
	(*GetOrderbookRequest)(nil),    // 0: eidos.matching.v1.GetOrderbookRequest
	(*GetOrderbookResponse)(nil),   // 1: eidos.matching.v1.GetOrderbookResponse
	(*GetDepthRequest)(nil),        // 2: eidos.matching.v1.GetDepthRequest
	(*GetDepthResponse)(nil),       // 3: eidos.matching.v1.GetDepthResponse
	(*PriceLevel)(nil),             // 4: eidos.matching.v1.PriceLevel
	(*HealthCheckRequest)(nil),     // 5: eidos.matching.v1.HealthCheckRequest
	(*HealthCheckResponse)(nil),    // 6: eidos.matching.v1.HealthCheckResponse
	(*MarketStatus)(nil),           // 7: eidos.matching.v1.MarketStatus
	(*OrderMessage)(nil),           // 8: eidos.matching.v1.OrderMessage
	(*CancelRequestMessage)(nil),   // 9: eidos.matching.v1.CancelRequestMessage
	(*TradeResultMessage)(nil),     // 10: eidos.matching.v1.TradeResultMessage
	(*OrderbookUpdateMessage)(nil), // 11: eidos.matching.v1.OrderbookUpdateMessage
	(*PriceLevelUpdate)(nil),       // 12: eidos.matching.v1.PriceLevelUpdate
	(*OrderCancelledMessage)(nil),  // 13: eidos.matching.v1.OrderCancelledMessage
	nil,                            // 14: eidos.matching.v1.HealthCheckResponse.MarketsEntry
	(v1.OrderSide)(0),              // 15: eidos.common.v1.OrderSide
	(v1.OrderType)(0),              // 16: eidos.common.v1.OrderType
	(v1.TimeInForce)(0),            // 17: eidos.common.v1.TimeInForce
}
var file_matching_v1_matching_proto_depIdxs = []int32{
	4,  // 0: eidos.matching.v1.GetOrderbookResponse.bids:type_name -> eidos.matching.v1.PriceLevel
	4,  // 1: eidos.matching.v1.GetOrderbookResponse.asks:type_name -> eidos.matching.v1.PriceLevel
	4,  // 2: eidos.matching.v1.GetDepthResponse.bids:type_name -> eidos.matching.v1.PriceLevel
	4,  // 3: eidos.matching.v1.GetDepthResponse.asks:type_name -> eidos.matching.v1.PriceLevel
	14, // 4: eidos.matching.v1.HealthCheckResponse.markets:type_name -> eidos.matching.v1.HealthCheckResponse.MarketsEntry
	15, // 5: eidos.matching.v1.OrderMessage.side:type_name -> eidos.common.v1.OrderSide
	16, // 6: eidos.matching.v1.OrderMessage.order_type:type_name -> eidos.common.v1.OrderType
	17, // 7: eidos.matching.v1.OrderMessage.time_in_force:type_name -> eidos.common.v1.TimeInForce
	15, // 8: eidos.matching.v1.TradeResultMessage.taker_side:type_name -> eidos.common.v1.OrderSide
	12, // 9: eidos.matching.v1.OrderbookUpdateMessage.bids:type_name -> eidos.matching.v1.PriceLevelUpdate
	12, // 10: eidos.matching.v1.OrderbookUpdateMessage.asks:type_name -> eidos.matching.v1.PriceLevelUpdate
	7,  // 11: eidos.matching.v1.HealthCheckResponse.MarketsEntry.value:type_name -> eidos.matching.v1.MarketStatus
	0,  // 12: eidos.matching.v1.MatchingService.GetOrderbook:input_type -> eidos.matching.v1.GetOrderbookRequest
	2,  // 13: eidos.matching.v1.MatchingService.GetDepth:input_type -> eidos.matching.v1.GetDepthRequest
	5,  // 14: eidos.matching.v1.MatchingService.HealthCheck:input_type -> eidos.matching.v1.HealthCheckRequest
	1,  // 15: eidos.matching.v1.MatchingService.GetOrderbook:output_type -> eidos.matching.v1.GetOrderbookResponse
	3,  // 16: eidos.matching.v1.MatchingService.GetDepth:output_type -> eidos.matching.v1.GetDepthResponse
	6,  // 17: eidos.matching.v1.MatchingService.HealthCheck:output_type -> eidos.matching.v1.HealthCheckResponse
	15, // [15:18] is the sub-list for method output_type
	12, // [12:15] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_matching_v1_matching_proto_init() }
func file_matching_v1_matching_proto_init() {
	if File_matching_v1_matching_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_matching_v1_matching_proto_rawDesc), len(file_matching_v1_matching_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_matching_v1_matching_proto_goTypes,
		DependencyIndexes: file_matching_v1_matching_proto_depIdxs,
		MessageInfos:      file_matching_v1_matching_proto_msgTypes,
	}.Build()
	File_matching_v1_matching_proto = out.File
	file_matching_v1_matching_proto_goTypes = nil
	file_matching_v1_matching_proto_depIdxs = nil
}
