// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: market/v1/market_service.proto

package marketv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MarketStatus 市场状态
type MarketStatus int32

const (
	MarketStatus_MARKET_STATUS_UNSPECIFIED MarketStatus = 0
	MarketStatus_MARKET_STATUS_INACTIVE    MarketStatus = 1
	MarketStatus_MARKET_STATUS_ACTIVE      MarketStatus = 2
	MarketStatus_MARKET_STATUS_SUSPEND     MarketStatus = 3
)

// Enum value maps for MarketStatus.
var (
	MarketStatus_name = map[int32]string{
		0: "MARKET_STATUS_UNSPECIFIED",
		1: "MARKET_STATUS_INACTIVE",
		2: "MARKET_STATUS_ACTIVE",
		3: "MARKET_STATUS_SUSPEND",
	}
	MarketStatus_value = map[string]int32{
		"MARKET_STATUS_UNSPECIFIED": 0,
		"MARKET_STATUS_INACTIVE":    1,
		"MARKET_STATUS_ACTIVE":      2,
		"MARKET_STATUS_SUSPEND":     3,
	}
)

func (x MarketStatus) Enum() *MarketStatus {
	p := new(MarketStatus)
	*p = x
	return p
}

func (x MarketStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MarketStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_market_v1_market_service_proto_enumTypes[0].Descriptor()
}

func (MarketStatus) Type() protoreflect.EnumType {
	return &file_market_v1_market_service_proto_enumTypes[0]
}

func (x MarketStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MarketStatus.Descriptor instead.
func (MarketStatus) EnumDescriptor() ([]byte, []int) {
	return file_market_v1_market_service_proto_rawDescGZIP(), []int{0}
}

// KlineInterval K 线周期
type KlineInterval int32

const (
	KlineInterval_KLINE_INTERVAL_UNSPECIFIED KlineInterval = 0
	KlineInterval_KLINE_INTERVAL_1M          KlineInterval = 1
	KlineInterval_KLINE_INTERVAL_5M          KlineInterval = 2
	KlineInterval_KLINE_INTERVAL_15M         KlineInterval = 3
	KlineInterval_KLINE_INTERVAL_30M         KlineInterval = 4
	KlineInterval_KLINE_INTERVAL_1H          KlineInterval = 5
	KlineInterval_KLINE_INTERVAL_4H          KlineInterval = 6
	KlineInterval_KLINE_INTERVAL_1D          KlineInterval = 7
	KlineInterval_KLINE_INTERVAL_1W          KlineInterval = 8
)

// Enum value maps for KlineInterval.
var (
	KlineInterval_name = map[int32]string{
		0: "KLINE_INTERVAL_UNSPECIFIED",
		1: "KLINE_INTERVAL_1M",
		2: "KLINE_INTERVAL_5M",
		3: "KLINE_INTERVAL_15M",
		4: "KLINE_INTERVAL_30M",
		5: "KLINE_INTERVAL_1H",
		6: "KLINE_INTERVAL_4H",
		7: "KLINE_INTERVAL_1D",
		8: "KLINE_INTERVAL_1W",
	}
	KlineInterval_value = map[string]int32{
		"KLINE_INTERVAL_UNSPECIFIED": 0,
		"KLINE_INTERVAL_1M":          1,
		"KLINE_INTERVAL_5M":          2,
		"KLINE_INTERVAL_15M":         3,
		"KLINE_INTERVAL_30M":         4,
		"KLINE_INTERVAL_1H":          5,
		"KLINE_INTERVAL_4H":          6,
		"KLINE_INTERVAL_1D":          7,
		"KLINE_INTERVAL_1W":          8,
	}
)

func (x KlineInterval) Enum() *KlineInterval {
	p := new(KlineInterval)
	*p = x
	return p
}

func (x KlineInterval) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (KlineInterval) Descriptor() protoreflect.EnumDescriptor {
	return file_market_v1_market_service_proto_enumTypes[1].Descriptor()
}

func (KlineInterval) Type() protoreflect.EnumType {
	return &file_market_v1_market_service_proto_enumTypes[1]
}

func (x KlineInterval) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use KlineInterval.Descriptor instead.
func (KlineInterval) EnumDescriptor() ([]byte, []int) {
	return file_market_v1_market_service_proto_rawDescGZIP(), []int{1}
}

// TradeSide 成交方向
type TradeSide int32

const (
	TradeSide_TRADE_SIDE_UNSPECIFIED TradeSide = 0
	TradeSide_TRADE_SIDE_BUY         TradeSide = 1
	TradeSide_TRADE_SIDE_SELL        TradeSide = 2
)

// Enum value maps for TradeSide.
var (
	TradeSide_name = map[int32]string{
		0: "TRADE_SIDE_UNSPECIFIED",
		1: "TRADE_SIDE_BUY",
		2: "TRADE_SIDE_SELL",
	}
	TradeSide_value = map[string]int32{
		"TRADE_SIDE_UNSPECIFIED": 0,
		"TRADE_SIDE_BUY":         1,
		"TRADE_SIDE_SELL":        2,
	}
)

func (x TradeSide) Enum() *TradeSide {
	p := new(TradeSide)
	*p = x
	return p
}

func (x TradeSide) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TradeSide) Descriptor() protoreflect.EnumDescriptor {
	return file_market_v1_market_service_proto_enumTypes[2].Descriptor()
}

func (TradeSide) Type() protoreflect.EnumType {
	return &file_market_v1_market_service_proto_enumTypes[2]
}

func (x TradeSide) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TradeSide.Descriptor instead.
func (TradeSide) EnumDescriptor() ([]byte, []int) {
	return file_market_v1_market_service_proto_rawDescGZIP(), []int{2}
}

// Market 交易对信息
type Market struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Symbol         string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`                                         // 交易对，如 "BTC-USDC"
	BaseToken      string                 `protobuf:"bytes,2,opt,name=base_token,json=baseToken,proto3" json:"base_token,omitempty"`                  // Base Token
	QuoteToken     string                 `protobuf:"bytes,3,opt,name=quote_token,json=quoteToken,proto3" json:"quote_token,omitempty"`               // Quote Token
	PriceDecimals  int32                  `protobuf:"varint,4,opt,name=price_decimals,json=priceDecimals,proto3" json:"price_decimals,omitempty"`     // 价格精度
	SizeDecimals   int32                  `protobuf:"varint,5,opt,name=size_decimals,json=sizeDecimals,proto3" json:"size_decimals,omitempty"`        // 数量精度
	MinSize        string                 `protobuf:"bytes,6,opt,name=min_size,json=minSize,proto3" json:"min_size,omitempty"`                        // 最小下单量
	MaxSize        string                 `protobuf:"bytes,7,opt,name=max_size,json=maxSize,proto3" json:"max_size,omitempty"`                        // 最大下单量
	MinNotional    string                 `protobuf:"bytes,8,opt,name=min_notional,json=minNotional,proto3" json:"min_notional,omitempty"`            // 最小名义价值
	TickSize       string                 `protobuf:"bytes,9,opt,name=tick_size,json=tickSize,proto3" json:"tick_size,omitempty"`                     // 最小价格变动
	MakerFee       string                 `protobuf:"bytes,10,opt,name=maker_fee,json=makerFee,proto3" json:"maker_fee,omitempty"`                    // Maker 手续费率
	TakerFee       string                 `protobuf:"bytes,11,opt,name=taker_fee,json=takerFee,proto3" json:"taker_fee,omitempty"`                    // Taker 手续费率
	Status         MarketStatus           `protobuf:"varint,12,opt,name=status,proto3,enum=eidos.market.v1.MarketStatus" json:"status,omitempty"`     // 状态
	TradingEnabled bool                   `protobuf:"varint,13,opt,name=trading_enabled,json=tradingEnabled,proto3" json:"trading_enabled,omitempty"` // 交易是否启用
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Market) Reset() {
	*x = Market{}
	mi := &file_market_v1_market_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Market) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Market) ProtoMessage() {}

func (x *Market) ProtoReflect() protoreflect.Message {
	mi := &file_market_v1_market_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Market.ProtoReflect.Descriptor instead.
func (*Market) Descriptor() ([]byte, []int) {
	return file_market_v1_market_service_proto_rawDescGZIP(), []int{0}
}

func (x *Market) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Market) GetBaseToken() string {
	if x != nil {
		return x.BaseToken
	}
	return ""
}

func (x *Market) GetQuoteToken() string {
	if x != nil {
		return x.QuoteToken
	}
	return ""
}

func (x *Market) GetPriceDecimals() int32 {
	if x != nil {
		return x.PriceDecimals
	}
	return 0
}

func (x *Market) GetSizeDecimals() int32 {
	if x != nil {
		return x.SizeDecimals
	}
	return 0
}

func (x *Market) GetMinSize() string {
	if x != nil {
		return x.MinSize
	}
	return ""
}

func (x *Market) GetMaxSize() string {
	if x != nil {
		return x.MaxSize
	}
	return ""
}

func (x *Market) GetMinNotional() string {
	if x != nil {
		return x.MinNotional
	}
	return ""
}

func (x *Market) GetTickSize() string {
	if x != nil {
		return x.TickSize
	}
	return ""
}

func (x *Market) GetMakerFee() string {
	if x != nil {
		return x.MakerFee
	}
	return ""
}

func (x *Market) GetTakerFee() string {
	if x != nil {
		return x.TakerFee
	}
	return ""
}

func (x *Market) GetStatus() MarketStatus {
	if x != nil {
		return x.Status
	}
	return MarketStatus_MARKET_STATUS_UNSPECIFIED
}

func (x *Market) GetTradingEnabled() bool {
	if x != nil {
		return x.TradingEnabled
	}
	return false
}

type ListMarketsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        MarketStatus           `protobuf:"varint,1,opt,name=status,proto3,enum=eidos.market.v1.MarketStatus" json:"status,omitempty"` // 筛选状态，UNSPECIFIED 表示全部
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMarketsRequest) Reset() {
	*x = ListMarketsRequest{}
	mi := &file_market_v1_market_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMarketsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMarketsRequest) ProtoMessage() {}

func (x *ListMarketsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_market_v1_market_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMarketsRequest.ProtoReflect.Descriptor instead.
func (*ListMarketsRequest) Descriptor() ([]byte, []int) {
	return file_market_v1_market_service_proto_rawDescGZIP(), []int{1}
}

func (x *ListMarketsRequest) GetStatus() MarketStatus {
	if x != nil {
		return x.Status
	}
	return MarketStatus_MARKET_STATUS_UNSPECIFIED
}

type ListMarketsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Markets       []*Market              `protobuf:"bytes,1,rep,name=markets,proto3" json:"markets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMarketsResponse) Reset() {
	*x = ListMarketsResponse{}
	mi := &file_market_v1_market_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMarketsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMarketsResponse) ProtoMessage() {}

func (x *ListMarketsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_market_v1_market_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMarketsResponse.ProtoReflect.Descriptor instead.
func (*ListMarketsResponse) Descriptor() ([]byte, []int) {
	return file_market_v1_market_service_proto_rawDescGZIP(), []int{2}
}

func (x *ListMarketsResponse) GetMarkets() []*Market {
	if x != nil {
		return x.Markets
	}
	return nil
}

// Ticker 24 小时行情
type Ticker struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Market             string                 `protobuf:"bytes,1,opt,name=market,proto3" json:"market,omitempty"`                                                     // 交易对
	LastPrice          string                 `protobuf:"bytes,2,opt,name=last_price,json=lastPrice,proto3" json:"last_price,omitempty"`                              // 最新价
	PriceChange        string                 `protobuf:"bytes,3,opt,name=price_change,json=priceChange,proto3" json:"price_change,omitempty"`                        // 24h 价格变化
	PriceChangePercent string                 `protobuf:"bytes,4,opt,name=price_change_percent,json=priceChangePercent,proto3" json:"price_change_percent,omitempty"` // 24h 价格变化百分比
	Open               string                 `protobuf:"bytes,5,opt,name=open,proto3" json:"open,omitempty"`                                                         // 24h 开盘价
	High               string                 `protobuf:"bytes,6,opt,name=high,proto3" json:"high,omitempty"`                                                         // 24h 最高价
	Low                string                 `protobuf:"bytes,7,opt,name=low,proto3" json:"low,omitempty"`                                                           // 24h 最低价
	Volume             string                 `protobuf:"bytes,8,opt,name=volume,proto3" json:"volume,omitempty"`                                                     // 24h 成交量 (Base)
	QuoteVolume        string                 `protobuf:"bytes,9,opt,name=quote_volume,json=quoteVolume,proto3" json:"quote_volume,omitempty"`                        // 24h 成交额 (Quote)
	BestBid            string                 `protobuf:"bytes,10,opt,name=best_bid,json=bestBid,proto3" json:"best_bid,omitempty"`                                   // 最优买价
	BestBidQty         string                 `protobuf:"bytes,11,opt,name=best_bid_qty,json=bestBidQty,proto3" json:"best_bid_qty,omitempty"`                        // 最优买价数量
	BestAsk            string                 `protobuf:"bytes,12,opt,name=best_ask,json=bestAsk,proto3" json:"best_ask,omitempty"`                                   // 最优卖价
	BestAskQty         string                 `protobuf:"bytes,13,opt,name=best_ask_qty,json=bestAskQty,proto3" json:"best_ask_qty,omitempty"`                        // 最优卖价数量
	TradeCount         int32                  `protobuf:"varint,14,opt,name=trade_count,json=tradeCount,proto3" json:"trade_count,omitempty"`                         // 24h 成交笔数
	Timestamp          int64                  `protobuf:"varint,15,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                             // 时间戳（毫秒）
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Ticker) Reset() {
	*x = Ticker{}
	mi := &file_market_v1_market_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ticker) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ticker) ProtoMessage() {}

func (x *Ticker) ProtoReflect() protoreflect.Message {
	mi := &file_market_v1_market_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ticker.ProtoReflect.Descriptor instead.
func (*Ticker) Descriptor() ([]byte, []int) {
	return file_market_v1_market_service_proto_rawDescGZIP(), []int{3}
}

func (x *Ticker) GetMarket() string {
	if x != nil {
		return x.Market
	}
	return ""
}

func (x *Ticker) GetLastPrice() string {
	if x != nil {
		return x.LastPrice
	}
	return ""
}

func (x *Ticker) GetPriceChange() string {
	if x != nil {
		return x.PriceChange
	}
	return ""
}

func (x *Ticker) GetPriceChangePercent() string {
	if x != nil {
		return x.PriceChangePercent
	}
	return ""
}

func (x *Ticker) GetOpen() string {
	if x != nil {
		return x.Open
	}
	return ""
}

func (x *Ticker) GetHigh() string {
	if x != nil {
		return x.High
	}
	return ""
}

func (x *Ticker) GetLow() string {
	if x != nil {
		return x.Low
	}
	return ""
}

func (x *Ticker) GetVolume() string {
	if x != nil {
		return x.Volume
	}
	return ""
}

func (x *Ticker) GetQuoteVolume() string {
	if x != nil {
		return x.QuoteVolume
	}
	return ""
}

func (x *Ticker) GetBestBid() string {
	if x != nil {
		return x.BestBid
	}
	return ""
}

func (x *Ticker) GetBestBidQty() string {
	if x != nil {
		return x.BestBidQty
	}
	return ""
}

func (x *Ticker) GetBestAsk() string {
	if x != nil {
		return x.BestAsk
	}
	return ""
}

func (x *Ticker) GetBestAskQty() string {
	if x != nil {
		return x.BestAskQty
	}
	return ""
}

func (x *Ticker) GetTradeCount() int32 {
	if x != nil {
		return x.TradeCount
	}
	return 0
}

func (x *Ticker) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type GetTickerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Market        string                 `protobuf:"bytes,1,opt,name=market,proto3" json:"market,omitempty"` // 交易对
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTickerRequest) Reset() {
	*x = GetTickerRequest{}
	mi := &file_market_v1_market_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTickerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTickerRequest) ProtoMessage() {}

func (x *GetTickerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_market_v1_market_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTickerRequest.ProtoReflect.Descriptor instead.
func (*GetTickerRequest) Descriptor() ([]byte, []int) {
	return file_market_v1_market_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetTickerRequest) GetMarket() string {
	if x != nil {
		return x.Market
	}
	return ""
}

type GetTickerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ticker        *Ticker                `protobuf:"bytes,1,opt,name=ticker,proto3" json:"ticker,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTickerResponse) Reset() {
	*x = GetTickerResponse{}
	mi := &file_market_v1_market_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTickerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTickerResponse) ProtoMessage() {}

func (x *GetTickerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_market_v1_market_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTickerResponse.ProtoReflect.Descriptor instead.
func (*GetTickerResponse) Descriptor() ([]byte, []int) {
	return file_market_v1_market_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetTickerResponse) GetTicker() *Ticker {
	if x != nil {
		return x.Ticker
	}
	return nil
}

type ListTickersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTickersRequest) Reset() {
	*x = ListTickersRequest{}
	mi := &file_market_v1_market_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTickersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTickersRequest) ProtoMessage() {}

func (x *ListTickersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_market_v1_market_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTickersRequest.ProtoReflect.Descriptor instead.
func (*ListTickersRequest) Descriptor() ([]byte, []int) {
	return file_market_v1_market_service_proto_rawDescGZIP(), []int{6}
}

type ListTickersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tickers       []*Ticker              `protobuf:"bytes,1,rep,name=tickers,proto3" json:"tickers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTickersResponse) Reset() {
	*x = ListTickersResponse{}
	mi := &file_market_v1_market_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTickersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTickersResponse) ProtoMessage() {}

func (x *ListTickersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_market_v1_market_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTickersResponse.ProtoReflect.Descriptor instead.
func (*ListTickersResponse) Descriptor() ([]byte, []int) {
	return file_market_v1_market_service_proto_rawDescGZIP(), []int{7}
}

func (x *ListTickersResponse) GetTickers() []*Ticker {
	if x != nil {
		return x.Tickers
	}
	return nil
}

// Kline K 线数据
type Kline struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Market        string                 `protobuf:"bytes,1,opt,name=market,proto3" json:"market,omitempty"`                              // 交易对
	Interval      string                 `protobuf:"bytes,2,opt,name=interval,proto3" json:"interval,omitempty"`                          // 周期
	OpenTime      int64                  `protobuf:"varint,3,opt,name=open_time,json=openTime,proto3" json:"open_time,omitempty"`         // 开盘时间（毫秒）
	Open          string                 `protobuf:"bytes,4,opt,name=open,proto3" json:"open,omitempty"`                                  // 开盘价
	High          string                 `protobuf:"bytes,5,opt,name=high,proto3" json:"high,omitempty"`                                  // 最高价
	Low           string                 `protobuf:"bytes,6,opt,name=low,proto3" json:"low,omitempty"`                                    // 最低价
	Close         string                 `protobuf:"bytes,7,opt,name=close,proto3" json:"close,omitempty"`                                // 收盘价
	Volume        string                 `protobuf:"bytes,8,opt,name=volume,proto3" json:"volume,omitempty"`                              // 成交量 (Base)
	QuoteVolume   string                 `protobuf:"bytes,9,opt,name=quote_volume,json=quoteVolume,proto3" json:"quote_volume,omitempty"` // 成交额 (Quote)
	TradeCount    int32                  `protobuf:"varint,10,opt,name=trade_count,json=tradeCount,proto3" json:"trade_count,omitempty"`  // 成交笔数
	CloseTime     int64                  `protobuf:"varint,11,opt,name=close_time,json=closeTime,proto3" json:"close_time,omitempty"`     // 收盘时间（毫秒）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Kline) Reset() {
	*x = Kline{}
	mi := &file_market_v1_market_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Kline) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Kline) ProtoMessage() {}

func (x *Kline) ProtoReflect() protoreflect.Message {
	mi := &file_market_v1_market_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Kline.ProtoReflect.Descriptor instead.
func (*Kline) Descriptor() ([]byte, []int) {
	return file_market_v1_market_service_proto_rawDescGZIP(), []int{8}
}

func (x *Kline) GetMarket() string {
	if x != nil {
		return x.Market
	}
	return ""
}

func (x *Kline) GetInterval() string {
	if x != nil {
		return x.Interval
	}
	return ""
}

func (x *Kline) GetOpenTime() int64 {
	if x != nil {
		return x.OpenTime
	}
	return 0
}

func (x *Kline) GetOpen() string {
	if x != nil {
		return x.Open
	}
	return ""
}

func (x *Kline) GetHigh() string {
	if x != nil {
		return x.High
	}
	return ""
}

func (x *Kline) GetLow() string {
	if x != nil {
		return x.Low
	}
	return ""
}

func (x *Kline) GetClose() string {
	if x != nil {
		return x.Close
	}
	return ""
}

func (x *Kline) GetVolume() string {
	if x != nil {
		return x.Volume
	}
	return ""
}

func (x *Kline) GetQuoteVolume() string {
	if x != nil {
		return x.QuoteVolume
	}
	return ""
}

func (x *Kline) GetTradeCount() int32 {
	if x != nil {
		return x.TradeCount
	}
	return 0
}

func (x *Kline) GetCloseTime() int64 {
	if x != nil {
		return x.CloseTime
	}
	return 0
}

type GetKlinesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Market        string                 `protobuf:"bytes,1,opt,name=market,proto3" json:"market,omitempty"`                         // 交易对
	Interval      string                 `protobuf:"bytes,2,opt,name=interval,proto3" json:"interval,omitempty"`                     // 周期: 1m, 5m, 15m, 30m, 1h, 4h, 1d, 1w
	StartTime     int64                  `protobuf:"varint,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"` // 开始时间（毫秒）
	EndTime       int64                  `protobuf:"varint,4,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`       // 结束时间（毫秒）
	Limit         int32                  `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`                          // 返回数量，默认 500，最大 1500
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKlinesRequest) Reset() {
	*x = GetKlinesRequest{}
	mi := &file_market_v1_market_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKlinesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKlinesRequest) ProtoMessage() {}

func (x *GetKlinesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_market_v1_market_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKlinesRequest.ProtoReflect.Descriptor instead.
func (*GetKlinesRequest) Descriptor() ([]byte, []int) {
	return file_market_v1_market_service_proto_rawDescGZIP(), []int{9}
}

func (x *GetKlinesRequest) GetMarket() string {
	if x != nil {
		return x.Market
	}
	return ""
}

func (x *GetKlinesRequest) GetInterval() string {
	if x != nil {
		return x.Interval
	}
	return ""
}

func (x *GetKlinesRequest) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *GetKlinesRequest) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *GetKlinesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetKlinesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Klines        []*Kline               `protobuf:"bytes,1,rep,name=klines,proto3" json:"klines,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKlinesResponse) Reset() {
	*x = GetKlinesResponse{}
	mi := &file_market_v1_market_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKlinesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKlinesResponse) ProtoMessage() {}

func (x *GetKlinesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_market_v1_market_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKlinesResponse.ProtoReflect.Descriptor instead.
func (*GetKlinesResponse) Descriptor() ([]byte, []int) {
	return file_market_v1_market_service_proto_rawDescGZIP(), []int{10}
}

func (x *GetKlinesResponse) GetKlines() []*Kline {
	if x != nil {
		return x.Klines
	}
	return nil
}

// RecentTrade 最近成交
type RecentTrade struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TradeId       string                 `protobuf:"bytes,1,opt,name=trade_id,json=tradeId,proto3" json:"trade_id,omitempty"`            // 成交 ID
	Market        string                 `protobuf:"bytes,2,opt,name=market,proto3" json:"market,omitempty"`                             // 交易对
	Price         string                 `protobuf:"bytes,3,opt,name=price,proto3" json:"price,omitempty"`                               // 成交价格
	Amount        string                 `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`                             // 成交数量
	Side          TradeSide              `protobuf:"varint,5,opt,name=side,proto3,enum=eidos.market.v1.TradeSide" json:"side,omitempty"` // Taker 方向
	Timestamp     int64                  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                      // 成交时间（毫秒）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecentTrade) Reset() {
	*x = RecentTrade{}
	mi := &file_market_v1_market_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecentTrade) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecentTrade) ProtoMessage() {}

func (x *RecentTrade) ProtoReflect() protoreflect.Message {
	mi := &file_market_v1_market_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecentTrade.ProtoReflect.Descriptor instead.
func (*RecentTrade) Descriptor() ([]byte, []int) {
	return file_market_v1_market_service_proto_rawDescGZIP(), []int{11}
}

func (x *RecentTrade) GetTradeId() string {
	if x != nil {
		return x.TradeId
	}
	return ""
}

func (x *RecentTrade) GetMarket() string {
	if x != nil {
		return x.Market
	}
	return ""
}

func (x *RecentTrade) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *RecentTrade) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *RecentTrade) GetSide() TradeSide {
	if x != nil {
		return x.Side
	}
	return TradeSide_TRADE_SIDE_UNSPECIFIED
}

func (x *RecentTrade) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type GetRecentTradesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Market        string                 `protobuf:"bytes,1,opt,name=market,proto3" json:"market,omitempty"` // 交易对
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`  // 返回数量，默认 50，最大 100
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecentTradesRequest) Reset() {
	*x = GetRecentTradesRequest{}
	mi := &file_market_v1_market_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecentTradesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecentTradesRequest) ProtoMessage() {}

func (x *GetRecentTradesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_market_v1_market_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecentTradesRequest.ProtoReflect.Descriptor instead.
func (*GetRecentTradesRequest) Descriptor() ([]byte, []int) {
	return file_market_v1_market_service_proto_rawDescGZIP(), []int{12}
}

func (x *GetRecentTradesRequest) GetMarket() string {
	if x != nil {
		return x.Market
	}
	return ""
}

func (x *GetRecentTradesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetRecentTradesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Trades        []*RecentTrade         `protobuf:"bytes,1,rep,name=trades,proto3" json:"trades,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecentTradesResponse) Reset() {
	*x = GetRecentTradesResponse{}
	mi := &file_market_v1_market_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecentTradesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecentTradesResponse) ProtoMessage() {}

func (x *GetRecentTradesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_market_v1_market_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecentTradesResponse.ProtoReflect.Descriptor instead.
func (*GetRecentTradesResponse) Descriptor() ([]byte, []int) {
	return file_market_v1_market_service_proto_rawDescGZIP(), []int{13}
}

func (x *GetRecentTradesResponse) GetTrades() []*RecentTrade {
	if x != nil {
		return x.Trades
	}
	return nil
}

// PriceLevel 价格档位
type PriceLevel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Price         string                 `protobuf:"bytes,1,opt,name=price,proto3" json:"price,omitempty"`   // 价格
	Amount        string                 `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"` // 数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PriceLevel) Reset() {
	*x = PriceLevel{}
	mi := &file_market_v1_market_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PriceLevel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriceLevel) ProtoMessage() {}

func (x *PriceLevel) ProtoReflect() protoreflect.Message {
	mi := &file_market_v1_market_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriceLevel.ProtoReflect.Descriptor instead.
func (*PriceLevel) Descriptor() ([]byte, []int) {
	return file_market_v1_market_service_proto_rawDescGZIP(), []int{14}
}

func (x *PriceLevel) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *PriceLevel) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

type GetDepthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Market        string                 `protobuf:"bytes,1,opt,name=market,proto3" json:"market,omitempty"` // 交易对
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`  // 档位数: 5, 10, 20, 50, 100，默认 20
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDepthRequest) Reset() {
	*x = GetDepthRequest{}
	mi := &file_market_v1_market_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDepthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDepthRequest) ProtoMessage() {}

func (x *GetDepthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_market_v1_market_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDepthRequest.ProtoReflect.Descriptor instead.
func (*GetDepthRequest) Descriptor() ([]byte, []int) {
	return file_market_v1_market_service_proto_rawDescGZIP(), []int{15}
}

func (x *GetDepthRequest) GetMarket() string {
	if x != nil {
		return x.Market
	}
	return ""
}

func (x *GetDepthRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetDepthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Market        string                 `protobuf:"bytes,1,opt,name=market,proto3" json:"market,omitempty"`
	Bids          []*PriceLevel          `protobuf:"bytes,2,rep,name=bids,proto3" json:"bids,omitempty"`            // 买单（价格降序）
	Asks          []*PriceLevel          `protobuf:"bytes,3,rep,name=asks,proto3" json:"asks,omitempty"`            // 卖单（价格升序）
	Sequence      uint64                 `protobuf:"varint,4,opt,name=sequence,proto3" json:"sequence,omitempty"`   // 序列号
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // 时间戳（毫秒）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDepthResponse) Reset() {
	*x = GetDepthResponse{}
	mi := &file_market_v1_market_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDepthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDepthResponse) ProtoMessage() {}

func (x *GetDepthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_market_v1_market_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDepthResponse.ProtoReflect.Descriptor instead.
func (*GetDepthResponse) Descriptor() ([]byte, []int) {
	return file_market_v1_market_service_proto_rawDescGZIP(), []int{16}
}

func (x *GetDepthResponse) GetMarket() string {
	if x != nil {
		return x.Market
	}
	return ""
}

func (x *GetDepthResponse) GetBids() []*PriceLevel {
	if x != nil {
		return x.Bids
	}
	return nil
}

func (x *GetDepthResponse) GetAsks() []*PriceLevel {
	if x != nil {
		return x.Asks
	}
	return nil
}

func (x *GetDepthResponse) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *GetDepthResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type Get24HStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Market        string                 `protobuf:"bytes,1,opt,name=market,proto3" json:"market,omitempty"` // 交易对
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Get24HStatsRequest) Reset() {
	*x = Get24HStatsRequest{}
	mi := &file_market_v1_market_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Get24HStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Get24HStatsRequest) ProtoMessage() {}

func (x *Get24HStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_market_v1_market_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Get24HStatsRequest.ProtoReflect.Descriptor instead.
func (*Get24HStatsRequest) Descriptor() ([]byte, []int) {
	return file_market_v1_market_service_proto_rawDescGZIP(), []int{17}
}

func (x *Get24HStatsRequest) GetMarket() string {
	if x != nil {
		return x.Market
	}
	return ""
}

type Get24HStatsResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Market             string                 `protobuf:"bytes,1,opt,name=market,proto3" json:"market,omitempty"`                                                     // 交易对
	PriceChange        string                 `protobuf:"bytes,2,opt,name=price_change,json=priceChange,proto3" json:"price_change,omitempty"`                        // 24h 价格变化
	PriceChangePercent string                 `protobuf:"bytes,3,opt,name=price_change_percent,json=priceChangePercent,proto3" json:"price_change_percent,omitempty"` // 24h 价格变化百分比
	High               string                 `protobuf:"bytes,4,opt,name=high,proto3" json:"high,omitempty"`                                                         // 24h 最高价
	Low                string                 `protobuf:"bytes,5,opt,name=low,proto3" json:"low,omitempty"`                                                           // 24h 最低价
	Volume             string                 `protobuf:"bytes,6,opt,name=volume,proto3" json:"volume,omitempty"`                                                     // 24h 成交量 (Base)
	QuoteVolume        string                 `protobuf:"bytes,7,opt,name=quote_volume,json=quoteVolume,proto3" json:"quote_volume,omitempty"`                        // 24h 成交额 (Quote)
	Open               string                 `protobuf:"bytes,8,opt,name=open,proto3" json:"open,omitempty"`                                                         // 24h 开盘价
	LastPrice          string                 `protobuf:"bytes,9,opt,name=last_price,json=lastPrice,proto3" json:"last_price,omitempty"`                              // 最新价
	TradeCount         int32                  `protobuf:"varint,10,opt,name=trade_count,json=tradeCount,proto3" json:"trade_count,omitempty"`                         // 24h 成交笔数
	Timestamp          int64                  `protobuf:"varint,11,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                             // 时间戳（毫秒）
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Get24HStatsResponse) Reset() {
	*x = Get24HStatsResponse{}
	mi := &file_market_v1_market_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Get24HStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Get24HStatsResponse) ProtoMessage() {}

func (x *Get24HStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_market_v1_market_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Get24HStatsResponse.ProtoReflect.Descriptor instead.
func (*Get24HStatsResponse) Descriptor() ([]byte, []int) {
	return file_market_v1_market_service_proto_rawDescGZIP(), []int{18}
}

func (x *Get24HStatsResponse) GetMarket() string {
	if x != nil {
		return x.Market
	}
	return ""
}

func (x *Get24HStatsResponse) GetPriceChange() string {
	if x != nil {
		return x.PriceChange
	}
	return ""
}

func (x *Get24HStatsResponse) GetPriceChangePercent() string {
	if x != nil {
		return x.PriceChangePercent
	}
	return ""
}

func (x *Get24HStatsResponse) GetHigh() string {
	if x != nil {
		return x.High
	}
	return ""
}

func (x *Get24HStatsResponse) GetLow() string {
	if x != nil {
		return x.Low
	}
	return ""
}

func (x *Get24HStatsResponse) GetVolume() string {
	if x != nil {
		return x.Volume
	}
	return ""
}

func (x *Get24HStatsResponse) GetQuoteVolume() string {
	if x != nil {
		return x.QuoteVolume
	}
	return ""
}

func (x *Get24HStatsResponse) GetOpen() string {
	if x != nil {
		return x.Open
	}
	return ""
}

func (x *Get24HStatsResponse) GetLastPrice() string {
	if x != nil {
		return x.LastPrice
	}
	return ""
}

func (x *Get24HStatsResponse) GetTradeCount() int32 {
	if x != nil {
		return x.TradeCount
	}
	return 0
}

func (x *Get24HStatsResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type GetTradeHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Market        string                 `protobuf:"bytes,1,opt,name=market,proto3" json:"market,omitempty"`                         // 交易对
	StartTime     int64                  `protobuf:"varint,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"` // 开始时间（毫秒）
	EndTime       int64                  `protobuf:"varint,3,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`       // 结束时间（毫秒）
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`                          // 返回数量，默认 100，最大 1000
	FromId        string                 `protobuf:"bytes,5,opt,name=from_id,json=fromId,proto3" json:"from_id,omitempty"`           // 从指定成交 ID 开始
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTradeHistoryRequest) Reset() {
	*x = GetTradeHistoryRequest{}
	mi := &file_market_v1_market_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTradeHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTradeHistoryRequest) ProtoMessage() {}

func (x *GetTradeHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_market_v1_market_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTradeHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetTradeHistoryRequest) Descriptor() ([]byte, []int) {
	return file_market_v1_market_service_proto_rawDescGZIP(), []int{19}
}

func (x *GetTradeHistoryRequest) GetMarket() string {
	if x != nil {
		return x.Market
	}
	return ""
}

func (x *GetTradeHistoryRequest) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *GetTradeHistoryRequest) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *GetTradeHistoryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetTradeHistoryRequest) GetFromId() string {
	if x != nil {
		return x.FromId
	}
	return ""
}

type GetTradeHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Trades        []*RecentTrade         `protobuf:"bytes,1,rep,name=trades,proto3" json:"trades,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTradeHistoryResponse) Reset() {
	*x = GetTradeHistoryResponse{}
	mi := &file_market_v1_market_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTradeHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTradeHistoryResponse) ProtoMessage() {}

func (x *GetTradeHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_market_v1_market_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTradeHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetTradeHistoryResponse) Descriptor() ([]byte, []int) {
	return file_market_v1_market_service_proto_rawDescGZIP(), []int{20}
}

func (x *GetTradeHistoryResponse) GetTrades() []*RecentTrade {
	if x != nil {
		return x.Trades
	}
	return nil
}

var File_market_v1_market_service_proto protoreflect.FileDescriptor

const file_market_v1_market_service_proto_rawDesc = "" +
	"\n" +
	"\x1emarket/v1/market_service.proto\x12\x0feidos.market.v1\"\xbc\x03\n" +
	"\x06Market\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x1d\n" +
	"\n" +
	"base_token\x18\x02 \x01(\tR\tbaseToken\x12\x1f\n" +
	"\vquote_token\x18\x03 \x01(\tR\n" +
	"quoteToken\x12%\n" +
	"\x0eprice_decimals\x18\x04 \x01(\x05R\rpriceDecimals\x12#\n" +
	"\rsize_decimals\x18\x05 \x01(\x05R\fsizeDecimals\x12\x19\n" +
	"\bmin_size\x18\x06 \x01(\tR\aminSize\x12\x19\n" +
	"\bmax_size\x18\a \x01(\tR\amaxSize\x12!\n" +
	"\fmin_notional\x18\b \x01(\tR\vminNotional\x12\x1b\n" +
	"\ttick_size\x18\t \x01(\tR\btickSize\x12\x1b\n" +
	"\tmaker_fee\x18\n" +
	" \x01(\tR\bmakerFee\x12\x1b\n" +
	"\ttaker_fee\x18\v \x01(\tR\btakerFee\x125\n" +
	"\x06status\x18\f \x01(\x0e2\x1d.eidos.market.v1.MarketStatusR\x06status\x12'\n" +
	"\x0ftrading_enabled\x18\r \x01(\bR\x0etradingEnabled\"K\n" +
	"\x12ListMarketsRequest\x125\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1d.eidos.market.v1.MarketStatusR\x06status\"H\n" +
	"\x13ListMarketsResponse\x121\n" +
	"\amarkets\x18\x01 \x03(\v2\x17.eidos.market.v1.MarketR\amarkets\"\xc2\x03\n" +
	"\x06Ticker\x12\x16\n" +
	"\x06market\x18\x01 \x01(\tR\x06market\x12\x1d\n" +
	"\n" +
	"last_price\x18\x02 \x01(\tR\tlastPrice\x12!\n" +
	"\fprice_change\x18\x03 \x01(\tR\vpriceChange\x120\n" +
	"\x14price_change_percent\x18\x04 \x01(\tR\x12priceChangePercent\x12\x12\n" +
	"\x04open\x18\x05 \x01(\tR\x04open\x12\x12\n" +
	"\x04high\x18\x06 \x01(\tR\x04high\x12\x10\n" +
	"\x03low\x18\a \x01(\tR\x03low\x12\x16\n" +
	"\x06volume\x18\b \x01(\tR\x06volume\x12!\n" +
	"\fquote_volume\x18\t \x01(\tR\vquoteVolume\x12\x19\n" +
	"\bbest_bid\x18\n" +
	" \x01(\tR\abestBid\x12 \n" +
	"\fbest_bid_qty\x18\v \x01(\tR\n" +
	"bestBidQty\x12\x19\n" +
	"\bbest_ask\x18\f \x01(\tR\abestAsk\x12 \n" +
	"\fbest_ask_qty\x18\r \x01(\tR\n" +
	"bestAskQty\x12\x1f\n" +
	"\vtrade_count\x18\x0e \x01(\x05R\n" +
	"tradeCount\x12\x1c\n" +
	"\ttimestamp\x18\x0f \x01(\x03R\ttimestamp\"*\n" +
	"\x10GetTickerRequest\x12\x16\n" +
	"\x06market\x18\x01 \x01(\tR\x06market\"D\n" +
	"\x11GetTickerResponse\x12/\n" +
	"\x06ticker\x18\x01 \x01(\v2\x17.eidos.market.v1.TickerR\x06ticker\"\x14\n" +
	"\x12ListTickersRequest\"H\n" +
	"\x13ListTickersResponse\x121\n" +
	"\atickers\x18\x01 \x03(\v2\x17.eidos.market.v1.TickerR\atickers\"\xa3\x02\n" +
	"\x05Kline\x12\x16\n" +
	"\x06market\x18\x01 \x01(\tR\x06market\x12\x1a\n" +
	"\binterval\x18\x02 \x01(\tR\binterval\x12\x1b\n" +
	"\topen_time\x18\x03 \x01(\x03R\bopenTime\x12\x12\n" +
	"\x04open\x18\x04 \x01(\tR\x04open\x12\x12\n" +
	"\x04high\x18\x05 \x01(\tR\x04high\x12\x10\n" +
	"\x03low\x18\x06 \x01(\tR\x03low\x12\x14\n" +
	"\x05close\x18\a \x01(\tR\x05close\x12\x16\n" +
	"\x06volume\x18\b \x01(\tR\x06volume\x12!\n" +
	"\fquote_volume\x18\t \x01(\tR\vquoteVolume\x12\x1f\n" +
	"\vtrade_count\x18\n" +
	" \x01(\x05R\n" +
	"tradeCount\x12\x1d\n" +
	"\n" +
	"close_time\x18\v \x01(\x03R\tcloseTime\"\x96\x01\n" +
	"\x10GetKlinesRequest\x12\x16\n" +
	"\x06market\x18\x01 \x01(\tR\x06market\x12\x1a\n" +
	"\binterval\x18\x02 \x01(\tR\binterval\x12\x1d\n" +
	"\n" +
	"start_time\x18\x03 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x04 \x01(\x03R\aendTime\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x05R\x05limit\"C\n" +
	"\x11GetKlinesResponse\x12.\n" +
	"\x06klines\x18\x01 \x03(\v2\x16.eidos.market.v1.KlineR\x06klines\"\xbc\x01\n" +
	"\vRecentTrade\x12\x19\n" +
	"\btrade_id\x18\x01 \x01(\tR\atradeId\x12\x16\n" +
	"\x06market\x18\x02 \x01(\tR\x06market\x12\x14\n" +
	"\x05price\x18\x03 \x01(\tR\x05price\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\tR\x06amount\x12.\n" +
	"\x04side\x18\x05 \x01(\x0e2\x1a.eidos.market.v1.TradeSideR\x04side\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp\"F\n" +
	"\x16GetRecentTradesRequest\x12\x16\n" +
	"\x06market\x18\x01 \x01(\tR\x06market\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"O\n" +
	"\x17GetRecentTradesResponse\x124\n" +
	"\x06trades\x18\x01 \x03(\v2\x1c.eidos.market.v1.RecentTradeR\x06trades\":\n" +
	"\n" +
	"PriceLevel\x12\x14\n" +
	"\x05price\x18\x01 \x01(\tR\x05price\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\tR\x06amount\"?\n" +
	"\x0fGetDepthRequest\x12\x16\n" +
	"\x06market\x18\x01 \x01(\tR\x06market\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"\xc6\x01\n" +
	"\x10GetDepthResponse\x12\x16\n" +
	"\x06market\x18\x01 \x01(\tR\x06market\x12/\n" +
	"\x04bids\x18\x02 \x03(\v2\x1b.eidos.market.v1.PriceLevelR\x04bids\x12/\n" +
	"\x04asks\x18\x03 \x03(\v2\x1b.eidos.market.v1.PriceLevelR\x04asks\x12\x1a\n" +
	"\bsequence\x18\x04 \x01(\x04R\bsequence\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\",\n" +
	"\x12Get24hStatsRequest\x12\x16\n" +
	"\x06market\x18\x01 \x01(\tR\x06market\"\xd5\x02\n" +
	"\x13Get24hStatsResponse\x12\x16\n" +
	"\x06market\x18\x01 \x01(\tR\x06market\x12!\n" +
	"\fprice_change\x18\x02 \x01(\tR\vpriceChange\x120\n" +
	"\x14price_change_percent\x18\x03 \x01(\tR\x12priceChangePercent\x12\x12\n" +
	"\x04high\x18\x04 \x01(\tR\x04high\x12\x10\n" +
	"\x03low\x18\x05 \x01(\tR\x03low\x12\x16\n" +
	"\x06volume\x18\x06 \x01(\tR\x06volume\x12!\n" +
	"\fquote_volume\x18\a \x01(\tR\vquoteVolume\x12\x12\n" +
	"\x04open\x18\b \x01(\tR\x04open\x12\x1d\n" +
	"\n" +
	"last_price\x18\t \x01(\tR\tlastPrice\x12\x1f\n" +
	"\vtrade_count\x18\n" +
	" \x01(\x05R\n" +
	"tradeCount\x12\x1c\n" +
	"\ttimestamp\x18\v \x01(\x03R\ttimestamp\"\x99\x01\n" +
	"\x16GetTradeHistoryRequest\x12\x16\n" +
	"\x06market\x18\x01 \x01(\tR\x06market\x12\x1d\n" +
	"\n" +
	"start_time\x18\x02 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x03 \x01(\x03R\aendTime\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\x12\x17\n" +
	"\afrom_id\x18\x05 \x01(\tR\x06fromId\"O\n" +
	"\x17GetTradeHistoryResponse\x124\n" +
	"\x06trades\x18\x01 \x03(\v2\x1c.eidos.market.v1.RecentTradeR\x06trades*~\n" +
	"\fMarketStatus\x12\x1d\n" +
	"\x19MARKET_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16MARKET_STATUS_INACTIVE\x10\x01\x12\x18\n" +
	"\x14MARKET_STATUS_ACTIVE\x10\x02\x12\x19\n" +
	"\x15MARKET_STATUS_SUSPEND\x10\x03*\xe9\x01\n" +
	"\rKlineInterval\x12\x1e\n" +
	"\x1aKLINE_INTERVAL_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11KLINE_INTERVAL_1M\x10\x01\x12\x15\n" +
	"\x11KLINE_INTERVAL_5M\x10\x02\x12\x16\n" +
	"\x12KLINE_INTERVAL_15M\x10\x03\x12\x16\n" +
	"\x12KLINE_INTERVAL_30M\x10\x04\x12\x15\n" +
	"\x11KLINE_INTERVAL_1H\x10\x05\x12\x15\n" +
	"\x11KLINE_INTERVAL_4H\x10\x06\x12\x15\n" +
	"\x11KLINE_INTERVAL_1D\x10\a\x12\x15\n" +
	"\x11KLINE_INTERVAL_1W\x10\b*P\n" +
	"\tTradeSide\x12\x1a\n" +
	"\x16TRADE_SIDE_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eTRADE_SIDE_BUY\x10\x01\x12\x13\n" +
	"\x0fTRADE_SIDE_SELL\x10\x022\xe2\x05\n" +
	"\rMarketService\x12X\n" +
	"\vListMarkets\x12#.eidos.market.v1.ListMarketsRequest\x1a$.eidos.market.v1.ListMarketsResponse\x12R\n" +
	"\tGetTicker\x12!.eidos.market.v1.GetTickerRequest\x1a\".eidos.market.v1.GetTickerResponse\x12X\n" +
	"\vListTickers\x12#.eidos.market.v1.ListTickersRequest\x1a$.eidos.market.v1.ListTickersResponse\x12R\n" +
	"\tGetKlines\x12!.eidos.market.v1.GetKlinesRequest\x1a\".eidos.market.v1.GetKlinesResponse\x12d\n" +
	"\x0fGetRecentTrades\x12'.eidos.market.v1.GetRecentTradesRequest\x1a(.eidos.market.v1.GetRecentTradesResponse\x12O\n" +
	"\bGetDepth\x12 .eidos.market.v1.GetDepthRequest\x1a!.eidos.market.v1.GetDepthResponse\x12X\n" +
	"\vGet24hStats\x12#.eidos.market.v1.Get24hStatsRequest\x1a$.eidos.market.v1.Get24hStatsResponse\x12d\n" +
	"\x0fGetTradeHistory\x12'.eidos.market.v1.GetTradeHistoryRequest\x1a(.eidos.market.v1.GetTradeHistoryResponseB:Z8github.com/eidos-exchange/eidos/proto/market/v1;marketv1b\x06proto3"

var (
	file_market_v1_market_service_proto_rawDescOnce sync.Once
	file_market_v1_market_service_proto_rawDescData []byte
)

func file_market_v1_market_service_proto_rawDescGZIP() []byte {
	file_market_v1_market_service_proto_rawDescOnce.Do(func() {
		file_market_v1_market_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_market_v1_market_service_proto_rawDesc), len(file_market_v1_market_service_proto_rawDesc)))
	})
	return file_market_v1_market_service_proto_rawDescData
}

var file_market_v1_market_service_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_market_v1_market_service_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_market_v1_market_service_proto_goTypes = []any{
	(MarketStatus)(0),               // 0: eidos.market.v1.MarketStatus
	(KlineInterval)(0),              // 1: eidos.market.v1.KlineInterval
	(TradeSide)(0),                  // 2: eidos.market.v1.TradeSide
	(*Market)(nil),                  // 3: eidos.market.v1.Market
	(*ListMarketsRequest)(nil),      // 4: eidos.market.v1.ListMarketsRequest
	(*ListMarketsResponse)(nil),     // 5: eidos.market.v1.ListMarketsResponse
	(*Ticker)(nil),                  // 6: eidos.market.v1.Ticker
	(*GetTickerRequest)(nil),        // 7: eidos.market.v1.GetTickerRequest
	(*GetTickerResponse)(nil),       // 8: eidos.market.v1.GetTickerResponse
	(*ListTickersRequest)(nil),      // 9: eidos.market.v1.ListTickersRequest
	(*ListTickersResponse)(nil),     // 10: eidos.market.v1.ListTickersResponse
	(*Kline)(nil),                   // 11: eidos.market.v1.Kline
	(*GetKlinesRequest)(nil),        // 12: eidos.market.v1.GetKlinesRequest
	(*GetKlinesResponse)(nil),       // 13: eidos.market.v1.GetKlinesResponse
	(*RecentTrade)(nil),             // 14: eidos.market.v1.RecentTrade
	(*GetRecentTradesRequest)(nil),  // 15: eidos.market.v1.GetRecentTradesRequest
	(*GetRecentTradesResponse)(nil), // 16: eidos.market.v1.GetRecentTradesResponse
	(*PriceLevel)(nil),              // 17: eidos.market.v1.PriceLevel
	(*GetDepthRequest)(nil),         // 18: eidos.market.v1.GetDepthRequest
	(*GetDepthResponse)(nil),        // 19: eidos.market.v1.GetDepthResponse
	(*Get24HStatsRequest)(nil),      // 20: eidos.market.v1.Get24hStatsRequest
	(*Get24HStatsResponse)(nil),     // 21: eidos.market.v1.Get24hStatsResponse
	(*GetTradeHistoryRequest)(nil),  // 22: eidos.market.v1.GetTradeHistoryRequest
	(*GetTradeHistoryResponse)(nil), // 23: eidos.market.v1.GetTradeHistoryResponse
}
var file_market_v1_market_service_proto_depIdxs = []int32{
	0,  // 0: eidos.market.v1.Market.status:type_name -> eidos.market.v1.MarketStatus
	0,  // 1: eidos.market.v1.ListMarketsRequest.status:type_name -> eidos.market.v1.MarketStatus
	3,  // 2: eidos.market.v1.ListMarketsResponse.markets:type_name -> eidos.market.v1.Market
	6,  // 3: eidos.market.v1.GetTickerResponse.ticker:type_name -> eidos.market.v1.Ticker
	6,  // 4: eidos.market.v1.ListTickersResponse.tickers:type_name -> eidos.market.v1.Ticker
	11, // 5: eidos.market.v1.GetKlinesResponse.klines:type_name -> eidos.market.v1.Kline
	2,  // 6: eidos.market.v1.RecentTrade.side:type_name -> eidos.market.v1.TradeSide
	14, // 7: eidos.market.v1.GetRecentTradesResponse.trades:type_name -> eidos.market.v1.RecentTrade
	17, // 8: eidos.market.v1.GetDepthResponse.bids:type_name -> eidos.market.v1.PriceLevel
	17, // 9: eidos.market.v1.GetDepthResponse.asks:type_name -> eidos.market.v1.PriceLevel
	14, // 10: eidos.market.v1.GetTradeHistoryResponse.trades:type_name -> eidos.market.v1.RecentTrade
	4,  // 11: eidos.market.v1.MarketService.ListMarkets:input_type -> eidos.market.v1.ListMarketsRequest
	7,  // 12: eidos.market.v1.MarketService.GetTicker:input_type -> eidos.market.v1.GetTickerRequest
	9,  // 13: eidos.market.v1.MarketService.ListTickers:input_type -> eidos.market.v1.ListTickersRequest
	12, // 14: eidos.market.v1.MarketService.GetKlines:input_type -> eidos.market.v1.GetKlinesRequest
	15, // 15: eidos.market.v1.MarketService.GetRecentTrades:input_type -> eidos.market.v1.GetRecentTradesRequest
	18, // 16: eidos.market.v1.MarketService.GetDepth:input_type -> eidos.market.v1.GetDepthRequest
	20, // 17: eidos.market.v1.MarketService.Get24hStats:input_type -> eidos.market.v1.Get24hStatsRequest
	22, // 18: eidos.market.v1.MarketService.GetTradeHistory:input_type -> eidos.market.v1.GetTradeHistoryRequest
	5,  // 19: eidos.market.v1.MarketService.ListMarkets:output_type -> eidos.market.v1.ListMarketsResponse
	8,  // 20: eidos.market.v1.MarketService.GetTicker:output_type -> eidos.market.v1.GetTickerResponse
	10, // 21: eidos.market.v1.MarketService.ListTickers:output_type -> eidos.market.v1.ListTickersResponse
	13, // 22: eidos.market.v1.MarketService.GetKlines:output_type -> eidos.market.v1.GetKlinesResponse
	16, // 23: eidos.market.v1.MarketService.GetRecentTrades:output_type -> eidos.market.v1.GetRecentTradesResponse
	19, // 24: eidos.market.v1.MarketService.GetDepth:output_type -> eidos.market.v1.GetDepthResponse
	21, // 25: eidos.market.v1.MarketService.Get24hStats:output_type -> eidos.market.v1.Get24hStatsResponse
	23, // 26: eidos.market.v1.MarketService.GetTradeHistory:output_type -> eidos.market.v1.GetTradeHistoryResponse
	19, // [19:27] is the sub-list for method output_type
	11, // [11:19] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_market_v1_market_service_proto_init() }
func file_market_v1_market_service_proto_init() {
	if File_market_v1_market_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_market_v1_market_service_proto_rawDesc), len(file_market_v1_market_service_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_market_v1_market_service_proto_goTypes,
		DependencyIndexes: file_market_v1_market_service_proto_depIdxs,
		EnumInfos:         file_market_v1_market_service_proto_enumTypes,
		MessageInfos:      file_market_v1_market_service_proto_msgTypes,
	}.Build()
	File_market_v1_market_service_proto = out.File
	file_market_v1_market_service_proto_goTypes = nil
	file_market_v1_market_service_proto_depIdxs = nil
}
