// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: chain/v1/chain.proto

package chainv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Settlement messages
type GetSettlementStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BatchId       string                 `protobuf:"bytes,1,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSettlementStatusRequest) Reset() {
	*x = GetSettlementStatusRequest{}
	mi := &file_chain_v1_chain_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSettlementStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSettlementStatusRequest) ProtoMessage() {}

func (x *GetSettlementStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chain_v1_chain_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSettlementStatusRequest.ProtoReflect.Descriptor instead.
func (*GetSettlementStatusRequest) Descriptor() ([]byte, []int) {
	return file_chain_v1_chain_proto_rawDescGZIP(), []int{0}
}

func (x *GetSettlementStatusRequest) GetBatchId() string {
	if x != nil {
		return x.BatchId
	}
	return ""
}

type GetSettlementStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Batch         *SettlementBatch       `protobuf:"bytes,1,opt,name=batch,proto3" json:"batch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSettlementStatusResponse) Reset() {
	*x = GetSettlementStatusResponse{}
	mi := &file_chain_v1_chain_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSettlementStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSettlementStatusResponse) ProtoMessage() {}

func (x *GetSettlementStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chain_v1_chain_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSettlementStatusResponse.ProtoReflect.Descriptor instead.
func (*GetSettlementStatusResponse) Descriptor() ([]byte, []int) {
	return file_chain_v1_chain_proto_rawDescGZIP(), []int{1}
}

func (x *GetSettlementStatusResponse) GetBatch() *SettlementBatch {
	if x != nil {
		return x.Batch
	}
	return nil
}

type RetrySettlementRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BatchId       string                 `protobuf:"bytes,1,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	SplitIfFailed bool                   `protobuf:"varint,2,opt,name=split_if_failed,json=splitIfFailed,proto3" json:"split_if_failed,omitempty"` // 失败时是否拆分批次
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetrySettlementRequest) Reset() {
	*x = RetrySettlementRequest{}
	mi := &file_chain_v1_chain_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrySettlementRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrySettlementRequest) ProtoMessage() {}

func (x *RetrySettlementRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chain_v1_chain_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrySettlementRequest.ProtoReflect.Descriptor instead.
func (*RetrySettlementRequest) Descriptor() ([]byte, []int) {
	return file_chain_v1_chain_proto_rawDescGZIP(), []int{2}
}

func (x *RetrySettlementRequest) GetBatchId() string {
	if x != nil {
		return x.BatchId
	}
	return ""
}

func (x *RetrySettlementRequest) GetSplitIfFailed() bool {
	if x != nil {
		return x.SplitIfFailed
	}
	return false
}

type RetrySettlementResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	NewBatchIds   []string               `protobuf:"bytes,3,rep,name=new_batch_ids,json=newBatchIds,proto3" json:"new_batch_ids,omitempty"` // 拆分后的新批次 ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetrySettlementResponse) Reset() {
	*x = RetrySettlementResponse{}
	mi := &file_chain_v1_chain_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrySettlementResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrySettlementResponse) ProtoMessage() {}

func (x *RetrySettlementResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chain_v1_chain_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrySettlementResponse.ProtoReflect.Descriptor instead.
func (*RetrySettlementResponse) Descriptor() ([]byte, []int) {
	return file_chain_v1_chain_proto_rawDescGZIP(), []int{3}
}

func (x *RetrySettlementResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RetrySettlementResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RetrySettlementResponse) GetNewBatchIds() []string {
	if x != nil {
		return x.NewBatchIds
	}
	return nil
}

type ListSettlementBatchesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"` // 可选，按状态过滤
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSettlementBatchesRequest) Reset() {
	*x = ListSettlementBatchesRequest{}
	mi := &file_chain_v1_chain_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSettlementBatchesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSettlementBatchesRequest) ProtoMessage() {}

func (x *ListSettlementBatchesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chain_v1_chain_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSettlementBatchesRequest.ProtoReflect.Descriptor instead.
func (*ListSettlementBatchesRequest) Descriptor() ([]byte, []int) {
	return file_chain_v1_chain_proto_rawDescGZIP(), []int{4}
}

func (x *ListSettlementBatchesRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ListSettlementBatchesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListSettlementBatchesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListSettlementBatchesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Batches       []*SettlementBatch     `protobuf:"bytes,1,rep,name=batches,proto3" json:"batches,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSettlementBatchesResponse) Reset() {
	*x = ListSettlementBatchesResponse{}
	mi := &file_chain_v1_chain_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSettlementBatchesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSettlementBatchesResponse) ProtoMessage() {}

func (x *ListSettlementBatchesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chain_v1_chain_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSettlementBatchesResponse.ProtoReflect.Descriptor instead.
func (*ListSettlementBatchesResponse) Descriptor() ([]byte, []int) {
	return file_chain_v1_chain_proto_rawDescGZIP(), []int{5}
}

func (x *ListSettlementBatchesResponse) GetBatches() []*SettlementBatch {
	if x != nil {
		return x.Batches
	}
	return nil
}

func (x *ListSettlementBatchesResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type SettlementBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BatchId       string                 `protobuf:"bytes,1,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	TradeCount    int32                  `protobuf:"varint,2,opt,name=trade_count,json=tradeCount,proto3" json:"trade_count,omitempty"`
	TradeIds      []string               `protobuf:"bytes,3,rep,name=trade_ids,json=tradeIds,proto3" json:"trade_ids,omitempty"`
	ChainId       int64                  `protobuf:"varint,4,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	TxHash        string                 `protobuf:"bytes,5,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	BlockNumber   int64                  `protobuf:"varint,6,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	GasUsed       int64                  `protobuf:"varint,7,opt,name=gas_used,json=gasUsed,proto3" json:"gas_used,omitempty"`
	GasPrice      string                 `protobuf:"bytes,8,opt,name=gas_price,json=gasPrice,proto3" json:"gas_price,omitempty"`
	Status        int32                  `protobuf:"varint,9,opt,name=status,proto3" json:"status,omitempty"` // 0=pending, 1=submitted, 2=confirmed, 3=failed
	ErrorMessage  string                 `protobuf:"bytes,10,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	RetryCount    int32                  `protobuf:"varint,11,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"`
	SubmittedAt   int64                  `protobuf:"varint,12,opt,name=submitted_at,json=submittedAt,proto3" json:"submitted_at,omitempty"`
	ConfirmedAt   int64                  `protobuf:"varint,13,opt,name=confirmed_at,json=confirmedAt,proto3" json:"confirmed_at,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,14,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SettlementBatch) Reset() {
	*x = SettlementBatch{}
	mi := &file_chain_v1_chain_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettlementBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettlementBatch) ProtoMessage() {}

func (x *SettlementBatch) ProtoReflect() protoreflect.Message {
	mi := &file_chain_v1_chain_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettlementBatch.ProtoReflect.Descriptor instead.
func (*SettlementBatch) Descriptor() ([]byte, []int) {
	return file_chain_v1_chain_proto_rawDescGZIP(), []int{6}
}

func (x *SettlementBatch) GetBatchId() string {
	if x != nil {
		return x.BatchId
	}
	return ""
}

func (x *SettlementBatch) GetTradeCount() int32 {
	if x != nil {
		return x.TradeCount
	}
	return 0
}

func (x *SettlementBatch) GetTradeIds() []string {
	if x != nil {
		return x.TradeIds
	}
	return nil
}

func (x *SettlementBatch) GetChainId() int64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *SettlementBatch) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *SettlementBatch) GetBlockNumber() int64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *SettlementBatch) GetGasUsed() int64 {
	if x != nil {
		return x.GasUsed
	}
	return 0
}

func (x *SettlementBatch) GetGasPrice() string {
	if x != nil {
		return x.GasPrice
	}
	return ""
}

func (x *SettlementBatch) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *SettlementBatch) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *SettlementBatch) GetRetryCount() int32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

func (x *SettlementBatch) GetSubmittedAt() int64 {
	if x != nil {
		return x.SubmittedAt
	}
	return 0
}

func (x *SettlementBatch) GetConfirmedAt() int64 {
	if x != nil {
		return x.ConfirmedAt
	}
	return 0
}

func (x *SettlementBatch) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

// Deposit messages
type GetDepositStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DepositId     string                 `protobuf:"bytes,1,opt,name=deposit_id,json=depositId,proto3" json:"deposit_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDepositStatusRequest) Reset() {
	*x = GetDepositStatusRequest{}
	mi := &file_chain_v1_chain_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDepositStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDepositStatusRequest) ProtoMessage() {}

func (x *GetDepositStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chain_v1_chain_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDepositStatusRequest.ProtoReflect.Descriptor instead.
func (*GetDepositStatusRequest) Descriptor() ([]byte, []int) {
	return file_chain_v1_chain_proto_rawDescGZIP(), []int{7}
}

func (x *GetDepositStatusRequest) GetDepositId() string {
	if x != nil {
		return x.DepositId
	}
	return ""
}

type GetDepositStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deposit       *DepositRecord         `protobuf:"bytes,1,opt,name=deposit,proto3" json:"deposit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDepositStatusResponse) Reset() {
	*x = GetDepositStatusResponse{}
	mi := &file_chain_v1_chain_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDepositStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDepositStatusResponse) ProtoMessage() {}

func (x *GetDepositStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chain_v1_chain_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDepositStatusResponse.ProtoReflect.Descriptor instead.
func (*GetDepositStatusResponse) Descriptor() ([]byte, []int) {
	return file_chain_v1_chain_proto_rawDescGZIP(), []int{8}
}

func (x *GetDepositStatusResponse) GetDeposit() *DepositRecord {
	if x != nil {
		return x.Deposit
	}
	return nil
}

type ListDepositsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WalletAddress string                 `protobuf:"bytes,1,opt,name=wallet_address,json=walletAddress,proto3" json:"wallet_address,omitempty"`
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"` // 可选
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDepositsRequest) Reset() {
	*x = ListDepositsRequest{}
	mi := &file_chain_v1_chain_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDepositsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDepositsRequest) ProtoMessage() {}

func (x *ListDepositsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chain_v1_chain_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDepositsRequest.ProtoReflect.Descriptor instead.
func (*ListDepositsRequest) Descriptor() ([]byte, []int) {
	return file_chain_v1_chain_proto_rawDescGZIP(), []int{9}
}

func (x *ListDepositsRequest) GetWalletAddress() string {
	if x != nil {
		return x.WalletAddress
	}
	return ""
}

func (x *ListDepositsRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ListDepositsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListDepositsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListDepositsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deposits      []*DepositRecord       `protobuf:"bytes,1,rep,name=deposits,proto3" json:"deposits,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDepositsResponse) Reset() {
	*x = ListDepositsResponse{}
	mi := &file_chain_v1_chain_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDepositsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDepositsResponse) ProtoMessage() {}

func (x *ListDepositsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chain_v1_chain_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDepositsResponse.ProtoReflect.Descriptor instead.
func (*ListDepositsResponse) Descriptor() ([]byte, []int) {
	return file_chain_v1_chain_proto_rawDescGZIP(), []int{10}
}

func (x *ListDepositsResponse) GetDeposits() []*DepositRecord {
	if x != nil {
		return x.Deposits
	}
	return nil
}

func (x *ListDepositsResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type DepositRecord struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	DepositId             string                 `protobuf:"bytes,1,opt,name=deposit_id,json=depositId,proto3" json:"deposit_id,omitempty"`
	WalletAddress         string                 `protobuf:"bytes,2,opt,name=wallet_address,json=walletAddress,proto3" json:"wallet_address,omitempty"`
	Token                 string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	TokenAddress          string                 `protobuf:"bytes,4,opt,name=token_address,json=tokenAddress,proto3" json:"token_address,omitempty"`
	Amount                string                 `protobuf:"bytes,5,opt,name=amount,proto3" json:"amount,omitempty"`
	ChainId               int64                  `protobuf:"varint,6,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	TxHash                string                 `protobuf:"bytes,7,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	BlockNumber           int64                  `protobuf:"varint,8,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	LogIndex              int32                  `protobuf:"varint,9,opt,name=log_index,json=logIndex,proto3" json:"log_index,omitempty"`
	Confirmations         int32                  `protobuf:"varint,10,opt,name=confirmations,proto3" json:"confirmations,omitempty"`
	RequiredConfirmations int32                  `protobuf:"varint,11,opt,name=required_confirmations,json=requiredConfirmations,proto3" json:"required_confirmations,omitempty"`
	Status                int32                  `protobuf:"varint,12,opt,name=status,proto3" json:"status,omitempty"` // 0=pending, 1=confirmed, 2=credited
	CreditedAt            int64                  `protobuf:"varint,13,opt,name=credited_at,json=creditedAt,proto3" json:"credited_at,omitempty"`
	CreatedAt             int64                  `protobuf:"varint,14,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *DepositRecord) Reset() {
	*x = DepositRecord{}
	mi := &file_chain_v1_chain_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepositRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepositRecord) ProtoMessage() {}

func (x *DepositRecord) ProtoReflect() protoreflect.Message {
	mi := &file_chain_v1_chain_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepositRecord.ProtoReflect.Descriptor instead.
func (*DepositRecord) Descriptor() ([]byte, []int) {
	return file_chain_v1_chain_proto_rawDescGZIP(), []int{11}
}

func (x *DepositRecord) GetDepositId() string {
	if x != nil {
		return x.DepositId
	}
	return ""
}

func (x *DepositRecord) GetWalletAddress() string {
	if x != nil {
		return x.WalletAddress
	}
	return ""
}

func (x *DepositRecord) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *DepositRecord) GetTokenAddress() string {
	if x != nil {
		return x.TokenAddress
	}
	return ""
}

func (x *DepositRecord) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *DepositRecord) GetChainId() int64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *DepositRecord) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *DepositRecord) GetBlockNumber() int64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *DepositRecord) GetLogIndex() int32 {
	if x != nil {
		return x.LogIndex
	}
	return 0
}

func (x *DepositRecord) GetConfirmations() int32 {
	if x != nil {
		return x.Confirmations
	}
	return 0
}

func (x *DepositRecord) GetRequiredConfirmations() int32 {
	if x != nil {
		return x.RequiredConfirmations
	}
	return 0
}

func (x *DepositRecord) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *DepositRecord) GetCreditedAt() int64 {
	if x != nil {
		return x.CreditedAt
	}
	return 0
}

func (x *DepositRecord) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

// Withdrawal messages
type GetWithdrawalStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WithdrawId    string                 `protobuf:"bytes,1,opt,name=withdraw_id,json=withdrawId,proto3" json:"withdraw_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWithdrawalStatusRequest) Reset() {
	*x = GetWithdrawalStatusRequest{}
	mi := &file_chain_v1_chain_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWithdrawalStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWithdrawalStatusRequest) ProtoMessage() {}

func (x *GetWithdrawalStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chain_v1_chain_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWithdrawalStatusRequest.ProtoReflect.Descriptor instead.
func (*GetWithdrawalStatusRequest) Descriptor() ([]byte, []int) {
	return file_chain_v1_chain_proto_rawDescGZIP(), []int{12}
}

func (x *GetWithdrawalStatusRequest) GetWithdrawId() string {
	if x != nil {
		return x.WithdrawId
	}
	return ""
}

type GetWithdrawalStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Withdrawal    *WithdrawalTx          `protobuf:"bytes,1,opt,name=withdrawal,proto3" json:"withdrawal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWithdrawalStatusResponse) Reset() {
	*x = GetWithdrawalStatusResponse{}
	mi := &file_chain_v1_chain_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWithdrawalStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWithdrawalStatusResponse) ProtoMessage() {}

func (x *GetWithdrawalStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chain_v1_chain_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWithdrawalStatusResponse.ProtoReflect.Descriptor instead.
func (*GetWithdrawalStatusResponse) Descriptor() ([]byte, []int) {
	return file_chain_v1_chain_proto_rawDescGZIP(), []int{13}
}

func (x *GetWithdrawalStatusResponse) GetWithdrawal() *WithdrawalTx {
	if x != nil {
		return x.Withdrawal
	}
	return nil
}

type RetryWithdrawalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WithdrawId    string                 `protobuf:"bytes,1,opt,name=withdraw_id,json=withdrawId,proto3" json:"withdraw_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetryWithdrawalRequest) Reset() {
	*x = RetryWithdrawalRequest{}
	mi := &file_chain_v1_chain_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryWithdrawalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryWithdrawalRequest) ProtoMessage() {}

func (x *RetryWithdrawalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chain_v1_chain_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryWithdrawalRequest.ProtoReflect.Descriptor instead.
func (*RetryWithdrawalRequest) Descriptor() ([]byte, []int) {
	return file_chain_v1_chain_proto_rawDescGZIP(), []int{14}
}

func (x *RetryWithdrawalRequest) GetWithdrawId() string {
	if x != nil {
		return x.WithdrawId
	}
	return ""
}

type RetryWithdrawalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetryWithdrawalResponse) Reset() {
	*x = RetryWithdrawalResponse{}
	mi := &file_chain_v1_chain_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryWithdrawalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryWithdrawalResponse) ProtoMessage() {}

func (x *RetryWithdrawalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chain_v1_chain_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryWithdrawalResponse.ProtoReflect.Descriptor instead.
func (*RetryWithdrawalResponse) Descriptor() ([]byte, []int) {
	return file_chain_v1_chain_proto_rawDescGZIP(), []int{15}
}

func (x *RetryWithdrawalResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RetryWithdrawalResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ListPendingWithdrawalsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WalletAddress string                 `protobuf:"bytes,1,opt,name=wallet_address,json=walletAddress,proto3" json:"wallet_address,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPendingWithdrawalsRequest) Reset() {
	*x = ListPendingWithdrawalsRequest{}
	mi := &file_chain_v1_chain_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPendingWithdrawalsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPendingWithdrawalsRequest) ProtoMessage() {}

func (x *ListPendingWithdrawalsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chain_v1_chain_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPendingWithdrawalsRequest.ProtoReflect.Descriptor instead.
func (*ListPendingWithdrawalsRequest) Descriptor() ([]byte, []int) {
	return file_chain_v1_chain_proto_rawDescGZIP(), []int{16}
}

func (x *ListPendingWithdrawalsRequest) GetWalletAddress() string {
	if x != nil {
		return x.WalletAddress
	}
	return ""
}

func (x *ListPendingWithdrawalsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListPendingWithdrawalsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListPendingWithdrawalsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Withdrawals   []*WithdrawalTx        `protobuf:"bytes,1,rep,name=withdrawals,proto3" json:"withdrawals,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPendingWithdrawalsResponse) Reset() {
	*x = ListPendingWithdrawalsResponse{}
	mi := &file_chain_v1_chain_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPendingWithdrawalsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPendingWithdrawalsResponse) ProtoMessage() {}

func (x *ListPendingWithdrawalsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chain_v1_chain_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPendingWithdrawalsResponse.ProtoReflect.Descriptor instead.
func (*ListPendingWithdrawalsResponse) Descriptor() ([]byte, []int) {
	return file_chain_v1_chain_proto_rawDescGZIP(), []int{17}
}

func (x *ListPendingWithdrawalsResponse) GetWithdrawals() []*WithdrawalTx {
	if x != nil {
		return x.Withdrawals
	}
	return nil
}

func (x *ListPendingWithdrawalsResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type WithdrawalTx struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WithdrawId    string                 `protobuf:"bytes,1,opt,name=withdraw_id,json=withdrawId,proto3" json:"withdraw_id,omitempty"`
	WalletAddress string                 `protobuf:"bytes,2,opt,name=wallet_address,json=walletAddress,proto3" json:"wallet_address,omitempty"`
	ToAddress     string                 `protobuf:"bytes,3,opt,name=to_address,json=toAddress,proto3" json:"to_address,omitempty"`
	Token         string                 `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
	TokenAddress  string                 `protobuf:"bytes,5,opt,name=token_address,json=tokenAddress,proto3" json:"token_address,omitempty"`
	Amount        string                 `protobuf:"bytes,6,opt,name=amount,proto3" json:"amount,omitempty"`
	ChainId       int64                  `protobuf:"varint,7,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	TxHash        string                 `protobuf:"bytes,8,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	BlockNumber   int64                  `protobuf:"varint,9,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	GasUsed       int64                  `protobuf:"varint,10,opt,name=gas_used,json=gasUsed,proto3" json:"gas_used,omitempty"`
	Status        int32                  `protobuf:"varint,11,opt,name=status,proto3" json:"status,omitempty"` // 0=pending, 1=submitted, 2=confirmed, 3=failed
	ErrorMessage  string                 `protobuf:"bytes,12,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	RetryCount    int32                  `protobuf:"varint,13,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"`
	SubmittedAt   int64                  `protobuf:"varint,14,opt,name=submitted_at,json=submittedAt,proto3" json:"submitted_at,omitempty"`
	ConfirmedAt   int64                  `protobuf:"varint,15,opt,name=confirmed_at,json=confirmedAt,proto3" json:"confirmed_at,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,16,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WithdrawalTx) Reset() {
	*x = WithdrawalTx{}
	mi := &file_chain_v1_chain_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WithdrawalTx) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithdrawalTx) ProtoMessage() {}

func (x *WithdrawalTx) ProtoReflect() protoreflect.Message {
	mi := &file_chain_v1_chain_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithdrawalTx.ProtoReflect.Descriptor instead.
func (*WithdrawalTx) Descriptor() ([]byte, []int) {
	return file_chain_v1_chain_proto_rawDescGZIP(), []int{18}
}

func (x *WithdrawalTx) GetWithdrawId() string {
	if x != nil {
		return x.WithdrawId
	}
	return ""
}

func (x *WithdrawalTx) GetWalletAddress() string {
	if x != nil {
		return x.WalletAddress
	}
	return ""
}

func (x *WithdrawalTx) GetToAddress() string {
	if x != nil {
		return x.ToAddress
	}
	return ""
}

func (x *WithdrawalTx) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *WithdrawalTx) GetTokenAddress() string {
	if x != nil {
		return x.TokenAddress
	}
	return ""
}

func (x *WithdrawalTx) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *WithdrawalTx) GetChainId() int64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *WithdrawalTx) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *WithdrawalTx) GetBlockNumber() int64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *WithdrawalTx) GetGasUsed() int64 {
	if x != nil {
		return x.GasUsed
	}
	return 0
}

func (x *WithdrawalTx) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *WithdrawalTx) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *WithdrawalTx) GetRetryCount() int32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

func (x *WithdrawalTx) GetSubmittedAt() int64 {
	if x != nil {
		return x.SubmittedAt
	}
	return 0
}

func (x *WithdrawalTx) GetConfirmedAt() int64 {
	if x != nil {
		return x.ConfirmedAt
	}
	return 0
}

func (x *WithdrawalTx) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

// Indexer messages
type GetIndexerStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChainId       int64                  `protobuf:"varint,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIndexerStatusRequest) Reset() {
	*x = GetIndexerStatusRequest{}
	mi := &file_chain_v1_chain_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIndexerStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIndexerStatusRequest) ProtoMessage() {}

func (x *GetIndexerStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chain_v1_chain_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIndexerStatusRequest.ProtoReflect.Descriptor instead.
func (*GetIndexerStatusRequest) Descriptor() ([]byte, []int) {
	return file_chain_v1_chain_proto_rawDescGZIP(), []int{19}
}

func (x *GetIndexerStatusRequest) GetChainId() int64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

type GetIndexerStatusResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ChainId         int64                  `protobuf:"varint,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	Running         bool                   `protobuf:"varint,2,opt,name=running,proto3" json:"running,omitempty"`
	CurrentBlock    uint64                 `protobuf:"varint,3,opt,name=current_block,json=currentBlock,proto3" json:"current_block,omitempty"`
	LatestBlock     uint64                 `protobuf:"varint,4,opt,name=latest_block,json=latestBlock,proto3" json:"latest_block,omitempty"`
	LagBlocks       int64                  `protobuf:"varint,5,opt,name=lag_blocks,json=lagBlocks,proto3" json:"lag_blocks,omitempty"`
	CheckpointBlock int64                  `protobuf:"varint,6,opt,name=checkpoint_block,json=checkpointBlock,proto3" json:"checkpoint_block,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetIndexerStatusResponse) Reset() {
	*x = GetIndexerStatusResponse{}
	mi := &file_chain_v1_chain_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIndexerStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIndexerStatusResponse) ProtoMessage() {}

func (x *GetIndexerStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chain_v1_chain_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIndexerStatusResponse.ProtoReflect.Descriptor instead.
func (*GetIndexerStatusResponse) Descriptor() ([]byte, []int) {
	return file_chain_v1_chain_proto_rawDescGZIP(), []int{20}
}

func (x *GetIndexerStatusResponse) GetChainId() int64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *GetIndexerStatusResponse) GetRunning() bool {
	if x != nil {
		return x.Running
	}
	return false
}

func (x *GetIndexerStatusResponse) GetCurrentBlock() uint64 {
	if x != nil {
		return x.CurrentBlock
	}
	return 0
}

func (x *GetIndexerStatusResponse) GetLatestBlock() uint64 {
	if x != nil {
		return x.LatestBlock
	}
	return 0
}

func (x *GetIndexerStatusResponse) GetLagBlocks() int64 {
	if x != nil {
		return x.LagBlocks
	}
	return 0
}

func (x *GetIndexerStatusResponse) GetCheckpointBlock() int64 {
	if x != nil {
		return x.CheckpointBlock
	}
	return 0
}

type GetBlockHeightRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChainId       int64                  `protobuf:"varint,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlockHeightRequest) Reset() {
	*x = GetBlockHeightRequest{}
	mi := &file_chain_v1_chain_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlockHeightRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlockHeightRequest) ProtoMessage() {}

func (x *GetBlockHeightRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chain_v1_chain_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlockHeightRequest.ProtoReflect.Descriptor instead.
func (*GetBlockHeightRequest) Descriptor() ([]byte, []int) {
	return file_chain_v1_chain_proto_rawDescGZIP(), []int{21}
}

func (x *GetBlockHeightRequest) GetChainId() int64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

type GetBlockHeightResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlockHeight   uint64                 `protobuf:"varint,1,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlockHeightResponse) Reset() {
	*x = GetBlockHeightResponse{}
	mi := &file_chain_v1_chain_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlockHeightResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlockHeightResponse) ProtoMessage() {}

func (x *GetBlockHeightResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chain_v1_chain_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlockHeightResponse.ProtoReflect.Descriptor instead.
func (*GetBlockHeightResponse) Descriptor() ([]byte, []int) {
	return file_chain_v1_chain_proto_rawDescGZIP(), []int{22}
}

func (x *GetBlockHeightResponse) GetBlockHeight() uint64 {
	if x != nil {
		return x.BlockHeight
	}
	return 0
}

func (x *GetBlockHeightResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// Reconciliation messages
type TriggerReconciliationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WalletAddress string                 `protobuf:"bytes,1,opt,name=wallet_address,json=walletAddress,proto3" json:"wallet_address,omitempty"` // 可选，为空则全量
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`                                      // 可选
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerReconciliationRequest) Reset() {
	*x = TriggerReconciliationRequest{}
	mi := &file_chain_v1_chain_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerReconciliationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerReconciliationRequest) ProtoMessage() {}

func (x *TriggerReconciliationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chain_v1_chain_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerReconciliationRequest.ProtoReflect.Descriptor instead.
func (*TriggerReconciliationRequest) Descriptor() ([]byte, []int) {
	return file_chain_v1_chain_proto_rawDescGZIP(), []int{23}
}

func (x *TriggerReconciliationRequest) GetWalletAddress() string {
	if x != nil {
		return x.WalletAddress
	}
	return ""
}

func (x *TriggerReconciliationRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type TriggerReconciliationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	TaskId        string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerReconciliationResponse) Reset() {
	*x = TriggerReconciliationResponse{}
	mi := &file_chain_v1_chain_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerReconciliationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerReconciliationResponse) ProtoMessage() {}

func (x *TriggerReconciliationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chain_v1_chain_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerReconciliationResponse.ProtoReflect.Descriptor instead.
func (*TriggerReconciliationResponse) Descriptor() ([]byte, []int) {
	return file_chain_v1_chain_proto_rawDescGZIP(), []int{24}
}

func (x *TriggerReconciliationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TriggerReconciliationResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TriggerReconciliationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetReconciliationStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReconciliationStatusRequest) Reset() {
	*x = GetReconciliationStatusRequest{}
	mi := &file_chain_v1_chain_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReconciliationStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReconciliationStatusRequest) ProtoMessage() {}

func (x *GetReconciliationStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chain_v1_chain_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReconciliationStatusRequest.ProtoReflect.Descriptor instead.
func (*GetReconciliationStatusRequest) Descriptor() ([]byte, []int) {
	return file_chain_v1_chain_proto_rawDescGZIP(), []int{25}
}

func (x *GetReconciliationStatusRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type GetReconciliationStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // running/completed/failed
	TotalChecked  int64                  `protobuf:"varint,3,opt,name=total_checked,json=totalChecked,proto3" json:"total_checked,omitempty"`
	Discrepancies int64                  `protobuf:"varint,4,opt,name=discrepancies,proto3" json:"discrepancies,omitempty"`
	StartedAt     int64                  `protobuf:"varint,5,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CompletedAt   int64                  `protobuf:"varint,6,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReconciliationStatusResponse) Reset() {
	*x = GetReconciliationStatusResponse{}
	mi := &file_chain_v1_chain_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReconciliationStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReconciliationStatusResponse) ProtoMessage() {}

func (x *GetReconciliationStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chain_v1_chain_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReconciliationStatusResponse.ProtoReflect.Descriptor instead.
func (*GetReconciliationStatusResponse) Descriptor() ([]byte, []int) {
	return file_chain_v1_chain_proto_rawDescGZIP(), []int{26}
}

func (x *GetReconciliationStatusResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *GetReconciliationStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetReconciliationStatusResponse) GetTotalChecked() int64 {
	if x != nil {
		return x.TotalChecked
	}
	return 0
}

func (x *GetReconciliationStatusResponse) GetDiscrepancies() int64 {
	if x != nil {
		return x.Discrepancies
	}
	return 0
}

func (x *GetReconciliationStatusResponse) GetStartedAt() int64 {
	if x != nil {
		return x.StartedAt
	}
	return 0
}

func (x *GetReconciliationStatusResponse) GetCompletedAt() int64 {
	if x != nil {
		return x.CompletedAt
	}
	return 0
}

type ListReconciliationRecordsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WalletAddress string                 `protobuf:"bytes,1,opt,name=wallet_address,json=walletAddress,proto3" json:"wallet_address,omitempty"` // 可选
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`                                    // 可选: OK/DISCREPANCY/RESOLVED/IGNORED
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReconciliationRecordsRequest) Reset() {
	*x = ListReconciliationRecordsRequest{}
	mi := &file_chain_v1_chain_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReconciliationRecordsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReconciliationRecordsRequest) ProtoMessage() {}

func (x *ListReconciliationRecordsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chain_v1_chain_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReconciliationRecordsRequest.ProtoReflect.Descriptor instead.
func (*ListReconciliationRecordsRequest) Descriptor() ([]byte, []int) {
	return file_chain_v1_chain_proto_rawDescGZIP(), []int{27}
}

func (x *ListReconciliationRecordsRequest) GetWalletAddress() string {
	if x != nil {
		return x.WalletAddress
	}
	return ""
}

func (x *ListReconciliationRecordsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListReconciliationRecordsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListReconciliationRecordsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListReconciliationRecordsResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Records       []*ReconciliationRecord `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	Total         int64                   `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReconciliationRecordsResponse) Reset() {
	*x = ListReconciliationRecordsResponse{}
	mi := &file_chain_v1_chain_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReconciliationRecordsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReconciliationRecordsResponse) ProtoMessage() {}

func (x *ListReconciliationRecordsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chain_v1_chain_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReconciliationRecordsResponse.ProtoReflect.Descriptor instead.
func (*ListReconciliationRecordsResponse) Descriptor() ([]byte, []int) {
	return file_chain_v1_chain_proto_rawDescGZIP(), []int{28}
}

func (x *ListReconciliationRecordsResponse) GetRecords() []*ReconciliationRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

func (x *ListReconciliationRecordsResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type ReconciliationRecord struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	WalletAddress     string                 `protobuf:"bytes,2,opt,name=wallet_address,json=walletAddress,proto3" json:"wallet_address,omitempty"`
	Token             string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	OnChainBalance    string                 `protobuf:"bytes,4,opt,name=on_chain_balance,json=onChainBalance,proto3" json:"on_chain_balance,omitempty"`
	OffChainSettled   string                 `protobuf:"bytes,5,opt,name=off_chain_settled,json=offChainSettled,proto3" json:"off_chain_settled,omitempty"`
	OffChainAvailable string                 `protobuf:"bytes,6,opt,name=off_chain_available,json=offChainAvailable,proto3" json:"off_chain_available,omitempty"`
	OffChainFrozen    string                 `protobuf:"bytes,7,opt,name=off_chain_frozen,json=offChainFrozen,proto3" json:"off_chain_frozen,omitempty"`
	PendingSettle     string                 `protobuf:"bytes,8,opt,name=pending_settle,json=pendingSettle,proto3" json:"pending_settle,omitempty"`
	Difference        string                 `protobuf:"bytes,9,opt,name=difference,proto3" json:"difference,omitempty"`
	Status            string                 `protobuf:"bytes,10,opt,name=status,proto3" json:"status,omitempty"`
	Resolution        string                 `protobuf:"bytes,11,opt,name=resolution,proto3" json:"resolution,omitempty"`
	ResolvedBy        string                 `protobuf:"bytes,12,opt,name=resolved_by,json=resolvedBy,proto3" json:"resolved_by,omitempty"`
	ResolvedAt        int64                  `protobuf:"varint,13,opt,name=resolved_at,json=resolvedAt,proto3" json:"resolved_at,omitempty"`
	CheckedAt         int64                  `protobuf:"varint,14,opt,name=checked_at,json=checkedAt,proto3" json:"checked_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ReconciliationRecord) Reset() {
	*x = ReconciliationRecord{}
	mi := &file_chain_v1_chain_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReconciliationRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconciliationRecord) ProtoMessage() {}

func (x *ReconciliationRecord) ProtoReflect() protoreflect.Message {
	mi := &file_chain_v1_chain_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReconciliationRecord.ProtoReflect.Descriptor instead.
func (*ReconciliationRecord) Descriptor() ([]byte, []int) {
	return file_chain_v1_chain_proto_rawDescGZIP(), []int{29}
}

func (x *ReconciliationRecord) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ReconciliationRecord) GetWalletAddress() string {
	if x != nil {
		return x.WalletAddress
	}
	return ""
}

func (x *ReconciliationRecord) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ReconciliationRecord) GetOnChainBalance() string {
	if x != nil {
		return x.OnChainBalance
	}
	return ""
}

func (x *ReconciliationRecord) GetOffChainSettled() string {
	if x != nil {
		return x.OffChainSettled
	}
	return ""
}

func (x *ReconciliationRecord) GetOffChainAvailable() string {
	if x != nil {
		return x.OffChainAvailable
	}
	return ""
}

func (x *ReconciliationRecord) GetOffChainFrozen() string {
	if x != nil {
		return x.OffChainFrozen
	}
	return ""
}

func (x *ReconciliationRecord) GetPendingSettle() string {
	if x != nil {
		return x.PendingSettle
	}
	return ""
}

func (x *ReconciliationRecord) GetDifference() string {
	if x != nil {
		return x.Difference
	}
	return ""
}

func (x *ReconciliationRecord) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ReconciliationRecord) GetResolution() string {
	if x != nil {
		return x.Resolution
	}
	return ""
}

func (x *ReconciliationRecord) GetResolvedBy() string {
	if x != nil {
		return x.ResolvedBy
	}
	return ""
}

func (x *ReconciliationRecord) GetResolvedAt() int64 {
	if x != nil {
		return x.ResolvedAt
	}
	return 0
}

func (x *ReconciliationRecord) GetCheckedAt() int64 {
	if x != nil {
		return x.CheckedAt
	}
	return 0
}

// Wallet messages
type GetWalletBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChainId       int64                  `protobuf:"varint,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	TokenAddress  string                 `protobuf:"bytes,2,opt,name=token_address,json=tokenAddress,proto3" json:"token_address,omitempty"` // 空表示 ETH
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWalletBalanceRequest) Reset() {
	*x = GetWalletBalanceRequest{}
	mi := &file_chain_v1_chain_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWalletBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWalletBalanceRequest) ProtoMessage() {}

func (x *GetWalletBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chain_v1_chain_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWalletBalanceRequest.ProtoReflect.Descriptor instead.
func (*GetWalletBalanceRequest) Descriptor() ([]byte, []int) {
	return file_chain_v1_chain_proto_rawDescGZIP(), []int{30}
}

func (x *GetWalletBalanceRequest) GetChainId() int64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *GetWalletBalanceRequest) GetTokenAddress() string {
	if x != nil {
		return x.TokenAddress
	}
	return ""
}

type GetWalletBalanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WalletAddress string                 `protobuf:"bytes,1,opt,name=wallet_address,json=walletAddress,proto3" json:"wallet_address,omitempty"`
	Balance       string                 `protobuf:"bytes,2,opt,name=balance,proto3" json:"balance,omitempty"`
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWalletBalanceResponse) Reset() {
	*x = GetWalletBalanceResponse{}
	mi := &file_chain_v1_chain_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWalletBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWalletBalanceResponse) ProtoMessage() {}

func (x *GetWalletBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chain_v1_chain_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWalletBalanceResponse.ProtoReflect.Descriptor instead.
func (*GetWalletBalanceResponse) Descriptor() ([]byte, []int) {
	return file_chain_v1_chain_proto_rawDescGZIP(), []int{31}
}

func (x *GetWalletBalanceResponse) GetWalletAddress() string {
	if x != nil {
		return x.WalletAddress
	}
	return ""
}

func (x *GetWalletBalanceResponse) GetBalance() string {
	if x != nil {
		return x.Balance
	}
	return ""
}

func (x *GetWalletBalanceResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type GetWalletNonceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChainId       int64                  `protobuf:"varint,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWalletNonceRequest) Reset() {
	*x = GetWalletNonceRequest{}
	mi := &file_chain_v1_chain_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWalletNonceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWalletNonceRequest) ProtoMessage() {}

func (x *GetWalletNonceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chain_v1_chain_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWalletNonceRequest.ProtoReflect.Descriptor instead.
func (*GetWalletNonceRequest) Descriptor() ([]byte, []int) {
	return file_chain_v1_chain_proto_rawDescGZIP(), []int{32}
}

func (x *GetWalletNonceRequest) GetChainId() int64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

type GetWalletNonceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WalletAddress string                 `protobuf:"bytes,1,opt,name=wallet_address,json=walletAddress,proto3" json:"wallet_address,omitempty"`
	CurrentNonce  uint64                 `protobuf:"varint,2,opt,name=current_nonce,json=currentNonce,proto3" json:"current_nonce,omitempty"`
	PendingCount  int32                  `protobuf:"varint,3,opt,name=pending_count,json=pendingCount,proto3" json:"pending_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWalletNonceResponse) Reset() {
	*x = GetWalletNonceResponse{}
	mi := &file_chain_v1_chain_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWalletNonceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWalletNonceResponse) ProtoMessage() {}

func (x *GetWalletNonceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chain_v1_chain_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWalletNonceResponse.ProtoReflect.Descriptor instead.
func (*GetWalletNonceResponse) Descriptor() ([]byte, []int) {
	return file_chain_v1_chain_proto_rawDescGZIP(), []int{33}
}

func (x *GetWalletNonceResponse) GetWalletAddress() string {
	if x != nil {
		return x.WalletAddress
	}
	return ""
}

func (x *GetWalletNonceResponse) GetCurrentNonce() uint64 {
	if x != nil {
		return x.CurrentNonce
	}
	return 0
}

func (x *GetWalletNonceResponse) GetPendingCount() int32 {
	if x != nil {
		return x.PendingCount
	}
	return 0
}

var File_chain_v1_chain_proto protoreflect.FileDescriptor

const file_chain_v1_chain_proto_rawDesc = "" +
	"\n" +
	"\x14chain/v1/chain.proto\x12\x0eeidos.chain.v1\"7\n" +
	"\x1aGetSettlementStatusRequest\x12\x19\n" +
	"\bbatch_id\x18\x01 \x01(\tR\abatchId\"T\n" +
	"\x1bGetSettlementStatusResponse\x125\n" +
	"\x05batch\x18\x01 \x01(\v2\x1f.eidos.chain.v1.SettlementBatchR\x05batch\"[\n" +
	"\x16RetrySettlementRequest\x12\x19\n" +
	"\bbatch_id\x18\x01 \x01(\tR\abatchId\x12&\n" +
	"\x0fsplit_if_failed\x18\x02 \x01(\bR\rsplitIfFailed\"q\n" +
	"\x17RetrySettlementResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\"\n" +
	"\rnew_batch_ids\x18\x03 \x03(\tR\vnewBatchIds\"g\n" +
	"\x1cListSettlementBatchesRequest\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"p\n" +
	"\x1dListSettlementBatchesResponse\x129\n" +
	"\abatches\x18\x01 \x03(\v2\x1f.eidos.chain.v1.SettlementBatchR\abatches\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"\xbc\x03\n" +
	"\x0fSettlementBatch\x12\x19\n" +
	"\bbatch_id\x18\x01 \x01(\tR\abatchId\x12\x1f\n" +
	"\vtrade_count\x18\x02 \x01(\x05R\n" +
	"tradeCount\x12\x1b\n" +
	"\ttrade_ids\x18\x03 \x03(\tR\btradeIds\x12\x19\n" +
	"\bchain_id\x18\x04 \x01(\x03R\achainId\x12\x17\n" +
	"\atx_hash\x18\x05 \x01(\tR\x06txHash\x12!\n" +
	"\fblock_number\x18\x06 \x01(\x03R\vblockNumber\x12\x19\n" +
	"\bgas_used\x18\a \x01(\x03R\agasUsed\x12\x1b\n" +
	"\tgas_price\x18\b \x01(\tR\bgasPrice\x12\x16\n" +
	"\x06status\x18\t \x01(\x05R\x06status\x12#\n" +
	"\rerror_message\x18\n" +
	" \x01(\tR\ferrorMessage\x12\x1f\n" +
	"\vretry_count\x18\v \x01(\x05R\n" +
	"retryCount\x12!\n" +
	"\fsubmitted_at\x18\f \x01(\x03R\vsubmittedAt\x12!\n" +
	"\fconfirmed_at\x18\r \x01(\x03R\vconfirmedAt\x12\x1d\n" +
	"\n" +
	"created_at\x18\x0e \x01(\x03R\tcreatedAt\"8\n" +
	"\x17GetDepositStatusRequest\x12\x1d\n" +
	"\n" +
	"deposit_id\x18\x01 \x01(\tR\tdepositId\"S\n" +
	"\x18GetDepositStatusResponse\x127\n" +
	"\adeposit\x18\x01 \x01(\v2\x1d.eidos.chain.v1.DepositRecordR\adeposit\"\x85\x01\n" +
	"\x13ListDepositsRequest\x12%\n" +
	"\x0ewallet_address\x18\x01 \x01(\tR\rwalletAddress\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"g\n" +
	"\x14ListDepositsResponse\x129\n" +
	"\bdeposits\x18\x01 \x03(\v2\x1d.eidos.chain.v1.DepositRecordR\bdeposits\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"\xd1\x03\n" +
	"\rDepositRecord\x12\x1d\n" +
	"\n" +
	"deposit_id\x18\x01 \x01(\tR\tdepositId\x12%\n" +
	"\x0ewallet_address\x18\x02 \x01(\tR\rwalletAddress\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\x12#\n" +
	"\rtoken_address\x18\x04 \x01(\tR\ftokenAddress\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\tR\x06amount\x12\x19\n" +
	"\bchain_id\x18\x06 \x01(\x03R\achainId\x12\x17\n" +
	"\atx_hash\x18\a \x01(\tR\x06txHash\x12!\n" +
	"\fblock_number\x18\b \x01(\x03R\vblockNumber\x12\x1b\n" +
	"\tlog_index\x18\t \x01(\x05R\blogIndex\x12$\n" +
	"\rconfirmations\x18\n" +
	" \x01(\x05R\rconfirmations\x125\n" +
	"\x16required_confirmations\x18\v \x01(\x05R\x15requiredConfirmations\x12\x16\n" +
	"\x06status\x18\f \x01(\x05R\x06status\x12\x1f\n" +
	"\vcredited_at\x18\r \x01(\x03R\n" +
	"creditedAt\x12\x1d\n" +
	"\n" +
	"created_at\x18\x0e \x01(\x03R\tcreatedAt\"=\n" +
	"\x1aGetWithdrawalStatusRequest\x12\x1f\n" +
	"\vwithdraw_id\x18\x01 \x01(\tR\n" +
	"withdrawId\"[\n" +
	"\x1bGetWithdrawalStatusResponse\x12<\n" +
	"\n" +
	"withdrawal\x18\x01 \x01(\v2\x1c.eidos.chain.v1.WithdrawalTxR\n" +
	"withdrawal\"9\n" +
	"\x16RetryWithdrawalRequest\x12\x1f\n" +
	"\vwithdraw_id\x18\x01 \x01(\tR\n" +
	"withdrawId\"M\n" +
	"\x17RetryWithdrawalResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"w\n" +
	"\x1dListPendingWithdrawalsRequest\x12%\n" +
	"\x0ewallet_address\x18\x01 \x01(\tR\rwalletAddress\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"v\n" +
	"\x1eListPendingWithdrawalsResponse\x12>\n" +
	"\vwithdrawals\x18\x01 \x03(\v2\x1c.eidos.chain.v1.WithdrawalTxR\vwithdrawals\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"\xfd\x03\n" +
	"\fWithdrawalTx\x12\x1f\n" +
	"\vwithdraw_id\x18\x01 \x01(\tR\n" +
	"withdrawId\x12%\n" +
	"\x0ewallet_address\x18\x02 \x01(\tR\rwalletAddress\x12\x1d\n" +
	"\n" +
	"to_address\x18\x03 \x01(\tR\ttoAddress\x12\x14\n" +
	"\x05token\x18\x04 \x01(\tR\x05token\x12#\n" +
	"\rtoken_address\x18\x05 \x01(\tR\ftokenAddress\x12\x16\n" +
	"\x06amount\x18\x06 \x01(\tR\x06amount\x12\x19\n" +
	"\bchain_id\x18\a \x01(\x03R\achainId\x12\x17\n" +
	"\atx_hash\x18\b \x01(\tR\x06txHash\x12!\n" +
	"\fblock_number\x18\t \x01(\x03R\vblockNumber\x12\x19\n" +
	"\bgas_used\x18\n" +
	" \x01(\x03R\agasUsed\x12\x16\n" +
	"\x06status\x18\v \x01(\x05R\x06status\x12#\n" +
	"\rerror_message\x18\f \x01(\tR\ferrorMessage\x12\x1f\n" +
	"\vretry_count\x18\r \x01(\x05R\n" +
	"retryCount\x12!\n" +
	"\fsubmitted_at\x18\x0e \x01(\x03R\vsubmittedAt\x12!\n" +
	"\fconfirmed_at\x18\x0f \x01(\x03R\vconfirmedAt\x12\x1d\n" +
	"\n" +
	"created_at\x18\x10 \x01(\x03R\tcreatedAt\"4\n" +
	"\x17GetIndexerStatusRequest\x12\x19\n" +
	"\bchain_id\x18\x01 \x01(\x03R\achainId\"\xe1\x01\n" +
	"\x18GetIndexerStatusResponse\x12\x19\n" +
	"\bchain_id\x18\x01 \x01(\x03R\achainId\x12\x18\n" +
	"\arunning\x18\x02 \x01(\bR\arunning\x12#\n" +
	"\rcurrent_block\x18\x03 \x01(\x04R\fcurrentBlock\x12!\n" +
	"\flatest_block\x18\x04 \x01(\x04R\vlatestBlock\x12\x1d\n" +
	"\n" +
	"lag_blocks\x18\x05 \x01(\x03R\tlagBlocks\x12)\n" +
	"\x10checkpoint_block\x18\x06 \x01(\x03R\x0fcheckpointBlock\"2\n" +
	"\x15GetBlockHeightRequest\x12\x19\n" +
	"\bchain_id\x18\x01 \x01(\x03R\achainId\"Y\n" +
	"\x16GetBlockHeightResponse\x12!\n" +
	"\fblock_height\x18\x01 \x01(\x04R\vblockHeight\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\"[\n" +
	"\x1cTriggerReconciliationRequest\x12%\n" +
	"\x0ewallet_address\x18\x01 \x01(\tR\rwalletAddress\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"l\n" +
	"\x1dTriggerReconciliationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"9\n" +
	"\x1eGetReconciliationStatusRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"\xdf\x01\n" +
	"\x1fGetReconciliationStatusResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12#\n" +
	"\rtotal_checked\x18\x03 \x01(\x03R\ftotalChecked\x12$\n" +
	"\rdiscrepancies\x18\x04 \x01(\x03R\rdiscrepancies\x12\x1d\n" +
	"\n" +
	"started_at\x18\x05 \x01(\x03R\tstartedAt\x12!\n" +
	"\fcompleted_at\x18\x06 \x01(\x03R\vcompletedAt\"\x92\x01\n" +
	" ListReconciliationRecordsRequest\x12%\n" +
	"\x0ewallet_address\x18\x01 \x01(\tR\rwalletAddress\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"y\n" +
	"!ListReconciliationRecordsResponse\x12>\n" +
	"\arecords\x18\x01 \x03(\v2$.eidos.chain.v1.ReconciliationRecordR\arecords\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"\xf3\x03\n" +
	"\x14ReconciliationRecord\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12%\n" +
	"\x0ewallet_address\x18\x02 \x01(\tR\rwalletAddress\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\x12(\n" +
	"\x10on_chain_balance\x18\x04 \x01(\tR\x0eonChainBalance\x12*\n" +
	"\x11off_chain_settled\x18\x05 \x01(\tR\x0foffChainSettled\x12.\n" +
	"\x13off_chain_available\x18\x06 \x01(\tR\x11offChainAvailable\x12(\n" +
	"\x10off_chain_frozen\x18\a \x01(\tR\x0eoffChainFrozen\x12%\n" +
	"\x0epending_settle\x18\b \x01(\tR\rpendingSettle\x12\x1e\n" +
	"\n" +
	"difference\x18\t \x01(\tR\n" +
	"difference\x12\x16\n" +
	"\x06status\x18\n" +
	" \x01(\tR\x06status\x12\x1e\n" +
	"\n" +
	"resolution\x18\v \x01(\tR\n" +
	"resolution\x12\x1f\n" +
	"\vresolved_by\x18\f \x01(\tR\n" +
	"resolvedBy\x12\x1f\n" +
	"\vresolved_at\x18\r \x01(\x03R\n" +
	"resolvedAt\x12\x1d\n" +
	"\n" +
	"checked_at\x18\x0e \x01(\x03R\tcheckedAt\"Y\n" +
	"\x17GetWalletBalanceRequest\x12\x19\n" +
	"\bchain_id\x18\x01 \x01(\x03R\achainId\x12#\n" +
	"\rtoken_address\x18\x02 \x01(\tR\ftokenAddress\"q\n" +
	"\x18GetWalletBalanceResponse\x12%\n" +
	"\x0ewallet_address\x18\x01 \x01(\tR\rwalletAddress\x12\x18\n" +
	"\abalance\x18\x02 \x01(\tR\abalance\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\"2\n" +
	"\x15GetWalletNonceRequest\x12\x19\n" +
	"\bchain_id\x18\x01 \x01(\x03R\achainId\"\x89\x01\n" +
	"\x16GetWalletNonceResponse\x12%\n" +
	"\x0ewallet_address\x18\x01 \x01(\tR\rwalletAddress\x12#\n" +
	"\rcurrent_nonce\x18\x02 \x01(\x04R\fcurrentNonce\x12#\n" +
	"\rpending_count\x18\x03 \x01(\x05R\fpendingCount2\xec\f\n" +
	"\fChainService\x12n\n" +
	"\x13GetSettlementStatus\x12*.eidos.chain.v1.GetSettlementStatusRequest\x1a+.eidos.chain.v1.GetSettlementStatusResponse\x12b\n" +
	"\x0fRetrySettlement\x12&.eidos.chain.v1.RetrySettlementRequest\x1a'.eidos.chain.v1.RetrySettlementResponse\x12t\n" +
	"\x15ListSettlementBatches\x12,.eidos.chain.v1.ListSettlementBatchesRequest\x1a-.eidos.chain.v1.ListSettlementBatchesResponse\x12e\n" +
	"\x10GetDepositStatus\x12'.eidos.chain.v1.GetDepositStatusRequest\x1a(.eidos.chain.v1.GetDepositStatusResponse\x12Y\n" +
	"\fListDeposits\x12#.eidos.chain.v1.ListDepositsRequest\x1a$.eidos.chain.v1.ListDepositsResponse\x12n\n" +
	"\x13GetWithdrawalStatus\x12*.eidos.chain.v1.GetWithdrawalStatusRequest\x1a+.eidos.chain.v1.GetWithdrawalStatusResponse\x12b\n" +
	"\x0fRetryWithdrawal\x12&.eidos.chain.v1.RetryWithdrawalRequest\x1a'.eidos.chain.v1.RetryWithdrawalResponse\x12w\n" +
	"\x16ListPendingWithdrawals\x12-.eidos.chain.v1.ListPendingWithdrawalsRequest\x1a..eidos.chain.v1.ListPendingWithdrawalsResponse\x12e\n" +
	"\x10GetIndexerStatus\x12'.eidos.chain.v1.GetIndexerStatusRequest\x1a(.eidos.chain.v1.GetIndexerStatusResponse\x12_\n" +
	"\x0eGetBlockHeight\x12%.eidos.chain.v1.GetBlockHeightRequest\x1a&.eidos.chain.v1.GetBlockHeightResponse\x12t\n" +
	"\x15TriggerReconciliation\x12,.eidos.chain.v1.TriggerReconciliationRequest\x1a-.eidos.chain.v1.TriggerReconciliationResponse\x12z\n" +
	"\x17GetReconciliationStatus\x12..eidos.chain.v1.GetReconciliationStatusRequest\x1a/.eidos.chain.v1.GetReconciliationStatusResponse\x12\x80\x01\n" +
	"\x19ListReconciliationRecords\x120.eidos.chain.v1.ListReconciliationRecordsRequest\x1a1.eidos.chain.v1.ListReconciliationRecordsResponse\x12e\n" +
	"\x10GetWalletBalance\x12'.eidos.chain.v1.GetWalletBalanceRequest\x1a(.eidos.chain.v1.GetWalletBalanceResponse\x12_\n" +
	"\x0eGetWalletNonce\x12%.eidos.chain.v1.GetWalletNonceRequest\x1a&.eidos.chain.v1.GetWalletNonceResponseB8Z6github.com/eidos-exchange/eidos/proto/chain/v1;chainv1b\x06proto3"

var (
	file_chain_v1_chain_proto_rawDescOnce sync.Once
	file_chain_v1_chain_proto_rawDescData []byte
)

func file_chain_v1_chain_proto_rawDescGZIP() []byte {
	file_chain_v1_chain_proto_rawDescOnce.Do(func() {
		file_chain_v1_chain_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chain_v1_chain_proto_rawDesc), len(file_chain_v1_chain_proto_rawDesc)))
	})
	return file_chain_v1_chain_proto_rawDescData
}

var file_chain_v1_chain_proto_msgTypes = make([]protoimpl.MessageInfo, 34)
var file_chain_v1_chain_proto_goTypes = []any{
	(*GetSettlementStatusRequest)(nil),        // 0: eidos.chain.v1.GetSettlementStatusRequest
	(*GetSettlementStatusResponse)(nil),       // 1: eidos.chain.v1.GetSettlementStatusResponse
	(*RetrySettlementRequest)(nil),            // 2: eidos.chain.v1.RetrySettlementRequest
	(*RetrySettlementResponse)(nil),           // 3: eidos.chain.v1.RetrySettlementResponse
	(*ListSettlementBatchesRequest)(nil),      // 4: eidos.chain.v1.ListSettlementBatchesRequest
	(*ListSettlementBatchesResponse)(nil),     // 5: eidos.chain.v1.ListSettlementBatchesResponse
	(*SettlementBatch)(nil),                   // 6: eidos.chain.v1.SettlementBatch
	(*GetDepositStatusRequest)(nil),           // 7: eidos.chain.v1.GetDepositStatusRequest
	(*GetDepositStatusResponse)(nil),          // 8: eidos.chain.v1.GetDepositStatusResponse
	(*ListDepositsRequest)(nil),               // 9: eidos.chain.v1.ListDepositsRequest
	(*ListDepositsResponse)(nil),              // 10: eidos.chain.v1.ListDepositsResponse
	(*DepositRecord)(nil),                     // 11: eidos.chain.v1.DepositRecord
	(*GetWithdrawalStatusRequest)(nil),        // 12: eidos.chain.v1.GetWithdrawalStatusRequest
	(*GetWithdrawalStatusResponse)(nil),       // 13: eidos.chain.v1.GetWithdrawalStatusResponse
	(*RetryWithdrawalRequest)(nil),            // 14: eidos.chain.v1.RetryWithdrawalRequest
	(*RetryWithdrawalResponse)(nil),           // 15: eidos.chain.v1.RetryWithdrawalResponse
	(*ListPendingWithdrawalsRequest)(nil),     // 16: eidos.chain.v1.ListPendingWithdrawalsRequest
	(*ListPendingWithdrawalsResponse)(nil),    // 17: eidos.chain.v1.ListPendingWithdrawalsResponse
	(*WithdrawalTx)(nil),                      // 18: eidos.chain.v1.WithdrawalTx
	(*GetIndexerStatusRequest)(nil),           // 19: eidos.chain.v1.GetIndexerStatusRequest
	(*GetIndexerStatusResponse)(nil),          // 20: eidos.chain.v1.GetIndexerStatusResponse
	(*GetBlockHeightRequest)(nil),             // 21: eidos.chain.v1.GetBlockHeightRequest
	(*GetBlockHeightResponse)(nil),            // 22: eidos.chain.v1.GetBlockHeightResponse
	(*TriggerReconciliationRequest)(nil),      // 23: eidos.chain.v1.TriggerReconciliationRequest
	(*TriggerReconciliationResponse)(nil),     // 24: eidos.chain.v1.TriggerReconciliationResponse
	(*GetReconciliationStatusRequest)(nil),    // 25: eidos.chain.v1.GetReconciliationStatusRequest
	(*GetReconciliationStatusResponse)(nil),   // 26: eidos.chain.v1.GetReconciliationStatusResponse
	(*ListReconciliationRecordsRequest)(nil),  // 27: eidos.chain.v1.ListReconciliationRecordsRequest
	(*ListReconciliationRecordsResponse)(nil), // 28: eidos.chain.v1.ListReconciliationRecordsResponse
	(*ReconciliationRecord)(nil),              // 29: eidos.chain.v1.ReconciliationRecord
	(*GetWalletBalanceRequest)(nil),           // 30: eidos.chain.v1.GetWalletBalanceRequest
	(*GetWalletBalanceResponse)(nil),          // 31: eidos.chain.v1.GetWalletBalanceResponse
	(*GetWalletNonceRequest)(nil),             // 32: eidos.chain.v1.GetWalletNonceRequest
	(*GetWalletNonceResponse)(nil),            // 33: eidos.chain.v1.GetWalletNonceResponse
}
var file_chain_v1_chain_proto_depIdxs = []int32{
	6,  // 0: eidos.chain.v1.GetSettlementStatusResponse.batch:type_name -> eidos.chain.v1.SettlementBatch
	6,  // 1: eidos.chain.v1.ListSettlementBatchesResponse.batches:type_name -> eidos.chain.v1.SettlementBatch
	11, // 2: eidos.chain.v1.GetDepositStatusResponse.deposit:type_name -> eidos.chain.v1.DepositRecord
	11, // 3: eidos.chain.v1.ListDepositsResponse.deposits:type_name -> eidos.chain.v1.DepositRecord
	18, // 4: eidos.chain.v1.GetWithdrawalStatusResponse.withdrawal:type_name -> eidos.chain.v1.WithdrawalTx
	18, // 5: eidos.chain.v1.ListPendingWithdrawalsResponse.withdrawals:type_name -> eidos.chain.v1.WithdrawalTx
	29, // 6: eidos.chain.v1.ListReconciliationRecordsResponse.records:type_name -> eidos.chain.v1.ReconciliationRecord
	0,  // 7: eidos.chain.v1.ChainService.GetSettlementStatus:input_type -> eidos.chain.v1.GetSettlementStatusRequest
	2,  // 8: eidos.chain.v1.ChainService.RetrySettlement:input_type -> eidos.chain.v1.RetrySettlementRequest
	4,  // 9: eidos.chain.v1.ChainService.ListSettlementBatches:input_type -> eidos.chain.v1.ListSettlementBatchesRequest
	7,  // 10: eidos.chain.v1.ChainService.GetDepositStatus:input_type -> eidos.chain.v1.GetDepositStatusRequest
	9,  // 11: eidos.chain.v1.ChainService.ListDeposits:input_type -> eidos.chain.v1.ListDepositsRequest
	12, // 12: eidos.chain.v1.ChainService.GetWithdrawalStatus:input_type -> eidos.chain.v1.GetWithdrawalStatusRequest
	14, // 13: eidos.chain.v1.ChainService.RetryWithdrawal:input_type -> eidos.chain.v1.RetryWithdrawalRequest
	16, // 14: eidos.chain.v1.ChainService.ListPendingWithdrawals:input_type -> eidos.chain.v1.ListPendingWithdrawalsRequest
	19, // 15: eidos.chain.v1.ChainService.GetIndexerStatus:input_type -> eidos.chain.v1.GetIndexerStatusRequest
	21, // 16: eidos.chain.v1.ChainService.GetBlockHeight:input_type -> eidos.chain.v1.GetBlockHeightRequest
	23, // 17: eidos.chain.v1.ChainService.TriggerReconciliation:input_type -> eidos.chain.v1.TriggerReconciliationRequest
	25, // 18: eidos.chain.v1.ChainService.GetReconciliationStatus:input_type -> eidos.chain.v1.GetReconciliationStatusRequest
	27, // 19: eidos.chain.v1.ChainService.ListReconciliationRecords:input_type -> eidos.chain.v1.ListReconciliationRecordsRequest
	30, // 20: eidos.chain.v1.ChainService.GetWalletBalance:input_type -> eidos.chain.v1.GetWalletBalanceRequest
	32, // 21: eidos.chain.v1.ChainService.GetWalletNonce:input_type -> eidos.chain.v1.GetWalletNonceRequest
	1,  // 22: eidos.chain.v1.ChainService.GetSettlementStatus:output_type -> eidos.chain.v1.GetSettlementStatusResponse
	3,  // 23: eidos.chain.v1.ChainService.RetrySettlement:output_type -> eidos.chain.v1.RetrySettlementResponse
	5,  // 24: eidos.chain.v1.ChainService.ListSettlementBatches:output_type -> eidos.chain.v1.ListSettlementBatchesResponse
	8,  // 25: eidos.chain.v1.ChainService.GetDepositStatus:output_type -> eidos.chain.v1.GetDepositStatusResponse
	10, // 26: eidos.chain.v1.ChainService.ListDeposits:output_type -> eidos.chain.v1.ListDepositsResponse
	13, // 27: eidos.chain.v1.ChainService.GetWithdrawalStatus:output_type -> eidos.chain.v1.GetWithdrawalStatusResponse
	15, // 28: eidos.chain.v1.ChainService.RetryWithdrawal:output_type -> eidos.chain.v1.RetryWithdrawalResponse
	17, // 29: eidos.chain.v1.ChainService.ListPendingWithdrawals:output_type -> eidos.chain.v1.ListPendingWithdrawalsResponse
	20, // 30: eidos.chain.v1.ChainService.GetIndexerStatus:output_type -> eidos.chain.v1.GetIndexerStatusResponse
	22, // 31: eidos.chain.v1.ChainService.GetBlockHeight:output_type -> eidos.chain.v1.GetBlockHeightResponse
	24, // 32: eidos.chain.v1.ChainService.TriggerReconciliation:output_type -> eidos.chain.v1.TriggerReconciliationResponse
	26, // 33: eidos.chain.v1.ChainService.GetReconciliationStatus:output_type -> eidos.chain.v1.GetReconciliationStatusResponse
	28, // 34: eidos.chain.v1.ChainService.ListReconciliationRecords:output_type -> eidos.chain.v1.ListReconciliationRecordsResponse
	31, // 35: eidos.chain.v1.ChainService.GetWalletBalance:output_type -> eidos.chain.v1.GetWalletBalanceResponse
	33, // 36: eidos.chain.v1.ChainService.GetWalletNonce:output_type -> eidos.chain.v1.GetWalletNonceResponse
	22, // [22:37] is the sub-list for method output_type
	7,  // [7:22] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_chain_v1_chain_proto_init() }
func file_chain_v1_chain_proto_init() {
	if File_chain_v1_chain_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chain_v1_chain_proto_rawDesc), len(file_chain_v1_chain_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   34,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chain_v1_chain_proto_goTypes,
		DependencyIndexes: file_chain_v1_chain_proto_depIdxs,
		MessageInfos:      file_chain_v1_chain_proto_msgTypes,
	}.Build()
	File_chain_v1_chain_proto = out.File
	file_chain_v1_chain_proto_goTypes = nil
	file_chain_v1_chain_proto_depIdxs = nil
}
